### ISSUE TITLE
Potential closure memory leak

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/area-model-common#101]
Investigating. Doesn't look like one where listeners are added, but memory is *slowly* going up during fuzzing, at like 10MB/hour.

I'll be investigating.

**Comment by jonathanolson** [comment]
Whoops, this looks like it's potentially due to our accessible keyboard drag listener (see https://github.com/phetsims/scenery/issues/764).

I'm going to hold off on thorough memory leak testing until that is done.

**Comment by jonathanolson** [comment]
I'll let the reviewers work on this together. I believe I worked around the keyboard drag issue, so that it removes the listener, so this should be ready.

**Comment by Denz1994** [comment]
Memory Leak Test: Several trials were run on separate chrome windows. Each sim was run twice on its own chrome window. One window was running standard chrome client the other was in the incognito mode. The two below test are examples of how heap comparisons were made. When heap growth subsided, the test was concluded.

From this, I didn't see any indication of a leak for all four sims.

Running on MacBookPro - Chrome Version: 65.0.3325.181 Incognito-page

CAM-Algebra:
1:40pm 77.5 MB
1:55pm 79.1 MB
2:15pm 80.4 MB
2:35pm 83.3 MB
2:50pm 82.1 MB
3:05pm 82.3 MB
3:20pm 83.3 MB

CAM-Multiplication:
4:20pm 69.6 MB
4:35pm  73.1 MB
4:50pm 75.2 MB
5:05pm  74.4 MB
5:15pm 74.3 MB

**Comment by samreid** [comment]
Looks great @Denz1994, thanks for running this test.  Assigned to @jonathanolson to review.  Also, @jonathanolson do we need to re-run tests with ?accessibility or any other flags?

**Comment by jonathanolson** [comment]
I'd be curious if area-model-introduction leaks with ?accessibility. Otherwise close if that is fine.

**Comment by phet-steele** [comment]
| 0:00 | 27.0 MB |
|  | MB |
|  | MB |
|  | MB |
|  | MB |

**Comment by phet-steele** [comment]
Sorry, pressed shift + enter. Will edit the above comment when the test is done.

**Comment by phet-steele** [comment]
@jonathanolson after 32 minutes, we are up to 44.2 MB with no sign of a plateau.

**Comment by lmulhall-phet** [comment]
Here's one without a11y:

0min - 25.0 MB
1min - 28.9 MB
2min - 32.0 MB
3min - 33.3 MB
4min - 33.6 MB
5min - 34.8 MB
6min - 34.8 MB
7min - 35.4 MB
8min - 35.7 MB
9min - 36.4 MB
10min - 36.3 MB

**Comment by jonathanolson** [comment]
I started fuzzing with the following:

- area-model-algebra_en_phet.html?fuzzMouse&screens=4
- area-model-introduction_en_phet.html?accessibility&fuzzMouse

I'll be noting values only coarsely. I'll also inspect snapshot comparisons once things are "warmed up".

**Comment by jonathanolson** [comment]
One leak is interesting. Creating a non-immutable Shape and then calling getStrokedBounds on it causes a technical leak of created listeners:

```js
var shape = new phet.kite.Shape()
      .moveTo( 1, 2 )
      .lineTo( 0, 0 )
      .lineTo( 3, 0 )
      .close();
shape.getStrokedBounds(); // call this a lot
shape.subpaths[0]._strokedSubpaths[0]._staticEventListeners
// {invalidated: Array(44)}
```

**Comment by jonathanolson** [comment]
Fix for the specific leak above committed. I'll continue evaluation in the other issue.
