### ISSUE TITLE
insufficient use of vegas in game

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/area-model-common#102]
Related to https://github.com/phetsims/area-model-common/issues/99

Area Model is not using common game components.

• Level-selection buttons are at GameAreaScreenView line 102.  It should be using LevelSelectionItemNodeDeprecated, or the newer LevelSelectionButton which will soon be replacing LevelSelectionItemNodeDeprecated.

• Status bar is implemented in GameStatusBar.  It should be using the well-established ScoreboardBar, which will need to be enhanced to show the score format used by Area Model.

• The score display is currently using ProgressIndicator, which is deprecated.  It should be using ScoreDisplayDiscreetStars.

**Comment by pixelzoom** [comment]
Beside the fact that game design should inform vegas, the other big reasons for using vegas components are a11y and phet-io.  If you use common-code, you'll get these features for free when the common-code is instrumented.  When you roll your own, you create more a11y and phet-io work.

**Comment by jonathanolson** [comment]
Switched to LevelSelectionButton above.

**Comment by jonathanolson** [comment]
Completed switch with the above commits.
