### ISSUE TITLE
Area-Model-Common/docs/images correct file location.

### ISSUE THREAD

**Issue by Denz1994** [phetsims/area-model-common#103]
During review of #99.

> Are all required files and directories present?
> For a sim repository named “my-repo”, the general structure should look like this (where assets/, audio/ or images/ may be omitted if the sim doesn’t have those types of assets).

The images found in ```Area-Model-Common/docs/images``` are used in the ```implementation-notes.md``` for documentation purposes. Should these images be placed in ```Area-Model-Common/images```? If not please close.

**Comment by jonathanolson** [comment]
@samreid, do we need to have license annotations for images that are unused in a sim?

Also, the brief decision at the dev meeting was to put them under doc/images/, and somewhere separate may be helpful to note "they are not used in the sim". If beneficial for licensing however, we could definitely move them (since we won't get unused image warnings due to it being a common repo, but that's not a great precedent).

**Comment by samreid** [comment]
I don't think we need to relicense images used in documentation, just in the sims, so they would not need to be annotated.

I agree the docs images should be in docs/images.

**Comment by jonathanolson** [comment]
@Denz1994, is there a place we can note in the checklist to note about doc/images?

**Comment by Denz1994** [comment]
@jonathanolson the checklist, we can add an ```images/```  directory under ```doc/```. What do you think?

#### **Repository structure**

- [ ] Are all required files and directories present?
For a sim repository named “my-repo”, the general structure should look like this (where assets/, audio/ or images/ may be omitted if the sim doesn’t have those types of assets).

```js
   my-repo/
      assets/
      audio/
         license.json
      doc/
         images/
               *see annotation
         model.md
         implementation-notes.md
      images/
         license.json
      js/
         (see section below)
      dependencies.json
      .gitignore
      my-repo_en.html
      my-repo-strings_en.json
      Gruntfile.js
      LICENSE
      package.json
      README.md
```
*Any images used in model.md or implementation-notes.md should be added here. Images specific to aiding with documentation do not need their own license.

**Comment by jonathanolson** [comment]
That looks good to me. In lieu of a dev meeting item to discuss the change, @samreid does the above change to the checklist look good to you?

**Comment by samreid** [comment]
That looks good, thanks, closing.

**Comment by samreid** [comment]
Back to @Denz1994 to see if there's anything else for this issue.

**Comment by Denz1994** [comment]
The code review checklist has been updated. Closing.
