### ISSUE TITLE
CountingTile string overlaps other panels.

### ISSUE THREAD

**Issue by Denz1994** [phetsims/area-model-common#104]
During review of #99:

> Does the sim layout gracefully handle internationalized strings that are exceptionally long? (run with query parameter stringTest=long)

![image](https://user-images.githubusercontent.com/13894380/38746180-c1183e3c-3f14-11e8-804f-8a8b17869e81.png)

Perhaps a maxWidth should be used ```ProportionalAreaScreenView.createCountingIconNode()```?

Does the '123' string even need to be translated?

**Comment by jonathanolson** [comment]
Yup, I definitely missed that.

While we're at it, @ariel-phet and @amanda-phet, should the '123' label for the counting checkbox be translatable? (If so I'll fix it up with a maxWidth).

**Comment by amanda-phet** [comment]
>should the '123' label for the counting checkbox be translatable? 

Do we normally allow numerals to be translated?

**Comment by pixelzoom** [comment]
@jonathanolson asked for my 2 cents on Slack.

> hmm… I think that’s probably a question for the designer.  The ‘123’ symbolizes ‘counting’.  If that symbolism is universal, then probably don’t need to translate.  If a locale has a better way of communicating what the checkbox does, then it would be useful to have it translatable — though I would expect 99.9% of translators to leave it as “123”.

**Comment by amanda-phet** [comment]
Thanks @pixelzoom . 

I think it would be fine to leave it as-is.

**Comment by ariel-phet** [comment]
I also think in this case it would be fine to leave untranslatable, I see that '123' as more of an icon in this case

**Comment by Denz1994** [comment]
Works great. Closing.
