### ISSUE TITLE
Screens directory contains screens for related Area-Model sims.

### ISSUE THREAD

**Issue by Denz1994** [phetsims/area-model-common#105]
During review of #99 

```Area-Model-Common/Screens``` contains screens for the other Area-Model sims. This structure is not used in CCK-Common and Fractions-Commons. In both CCK and Fractions, each sim has its own ```Sim/common/view``` with its own SimScreenView.js and SimScreen.js

Containing all of the related sims screens and views in Area-Model-Common seems to go against this convention.

**Comment by jonathanolson** [comment]
> Containing all of the related sims screens and views in Area-Model-Common seems to go against this convention.

I'd argue that some flexibility here is desired. Since CCK and Fractions don't use identical screens across multiple sims, their code layout works for that. In addition, if we had to pick one, I'd slightly prefer the screens in the common repo (so that code/options aren't copied).

This is probably worth discussion at the dev meeting.

**Comment by samreid** [comment]
In my review of #99 I found that the directory structure was unconventional, but well-tailored to the problem-at-hand:

* all screens in one directory
* main separation is around game vs proportional vs generic

The models and views from the game/proportional/generic screens are mixed and matched to make the 8 screens across 4 sims.

One possibility I considered would be to move game/ and generic/ and proportional/ under common/ then to move each of the screens to their own directory, so the directory structure would be:

![image](https://user-images.githubusercontent.com/679486/38912332-e72eb440-4291-11e8-8948-d2107110c7f8.png)

But this doesn't feel like an improvement to me (more of a lateral move).  Yes, generic and proportional should be "common" but they are already in a repo called "area-model-common".  Given that this is a common repo and not a sim repo, it seems OK to use a different pattern for structuring the screens.

That being said, I'd love to hear what others have to say about it.

**Comment by zepumph** [comment]
>Given that this is a common repo and not a sim repo, it seems OK to use a different pattern for structuring the screens.

I agree, and it seems like all screens in a single dir is crisp and clear to me, albeit not phet conventional . . . (yet).

**Comment by jbphet** [comment]
I agree that it is okay in this sim, which is unusual so far, to have the screens in the common repo.  The one caveat is that these screens **only** go into the common repo if they appear in multiple simulations, otherwise they should be in the sim repo.

**Comment by samreid** [comment]
In Area Model, DecimalsScreen is only used in area-model-decimals.  But it is such a thin wrapper that I suspect it will be easier to maintain in area-model-common.  For instance, if ProportionalAreaModel or ProportionalAreaScreenView interfaces change, then DecimalsScreen would change accordingly, and it would be trivial to find usages without searching across repos.  Applying the same argument to area-model-decimals-main.js reveals an absurd conclusion (obviously that should be in the sim directory).

**Comment by jonathanolson** [comment]
> The one caveat is that these screens only go into the common repo if they appear in multiple simulations, otherwise they should be in the sim repo.

So if screens (during development) move from being in 1 sim to multiple (or vice versa), we would move the screen to a different repo (making history difficult to check)?

**Comment by pixelzoom** [comment]
Self-assigning to review before dev meeting, since this one is going to take me a little more time than I have right now.

**Comment by pixelzoom** [comment]
Current approach is unusual, but fine with me.

**Comment by samreid** [comment]
At developer meeting, we agreed that keeping all the screens together will work well for this family of sims.
