### ISSUE TITLE
Twixt and Vibe dependencies in package.json?

### ISSUE THREAD

**Issue by Denz1994** [phetsims/area-model-common#107]
During the review of #99:

>  Does package.json refer to any dependencies that are not used by the sim?

I don't see any usages of Twixt or Vibe. Can these be removed from the ```package.json``` dependecies?

**Comment by Denz1994** [comment]
Twixt is now being used due to commit d9087cfa753023d1a5edfb3f3fc6f264b5e4a3e7 for https://github.com/phetsims/area-model-common/issues/65.

**Comment by jonathanolson** [comment]
SlidingScreen always depended on TWIXT, and GameAudioPlayer (used in GameAudio) depends on VIBE, so I believe they are both used.

**Comment by Denz1994** [comment]
Understood. Closing.
