### ISSUE TITLE
Update Credits

### ISSUE THREAD

**Issue by Denz1994** [phetsims/area-model-common#108]
During the review of #99:

> Does a GitHub issue exist for tracking credits, to ensure that they are correct before publication?

Creating this issue so we don't forget to update credits.

**Comment by jonathanolson** [comment]
Unassigning as there's nothing I can do now. Will happen before publication.

**Comment by jonathanolson** [comment]
With branching imminent, can @amanda-phet and @phet-steele anticipate the credits that will be used? This can be done after branching if necessary, but I want to make sure it doesn't get skipped.

**Comment by jonathanolson** [comment]
Assigning myself for a first pass at the credits (I'll grab things from the design docs, etc).

**Comment by jonathanolson** [comment]
Took a shot at it, feel free to change.

**Comment by amanda-phet** [comment]
Can you add Mariah Hermsmeyer to graphic arts? She drew the PhET girl that is used on the game screen icon (and we will likely be using PhET girl for the level selection icons). Can you also make sure she is listed for the license for the specific PhET girl image that is used in the game screen icons?

**Comment by jonathanolson** [comment]
Updated.

**Comment by phet-steele** [comment]
QA updated.

**Comment by amanda-phet** [comment]
My work here is done.
