### ISSUE TITLE
Layout for the 3rd screen

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/area-model-common#11]
I'm wondering where to potentially place the factor labels on the 3rd screen (and show the largest constraints):

Widest calculation with the current font size:
![screen shot 2017-05-12 at 4 55 06 pm](https://cloud.githubusercontent.com/assets/480878/26019802/a49542b0-3735-11e7-94d4-5acdbdbf27b9.png)

Widest simplified sum of the left side:
![screen shot 2017-05-12 at 4 55 35 pm](https://cloud.githubusercontent.com/assets/480878/26019806/ace58baa-3735-11e7-8700-4459fc6d2412.png)

Tallest calculation with the current font size:
![screen shot 2017-05-12 at 5 03 49 pm](https://cloud.githubusercontent.com/assets/480878/26019809/b32645cc-3735-11e7-83ce-199c3af0aa90.png)

Thoughts? Also, is it too disruptive to resize the calculation border to fit the formula? (Would change a lot while dragging on the 1st screen / decimal screen, but that doesn't apply to the generic screens).

**Comment by jonathanolson** [comment]
I think I may try automatic resizing to see how it feels (centered below the main area when possible, then expanding to the right).

**Comment by amyh-phet** [comment]
Here's my initial thoughts:

- Reduce the font size we use for factors when this option is chosen in Partial products panel.  I think we need to find a balance between large enough to read but small enough to fit. I'll be working on Monday to try out some ideas for an overlay (as discussed in design meeting), but I'd like to see if reducing font size helps too.
- Keep font size in calculation panel as currently implemented.  
-Try automatic resizing of calculation panel (centered, resizing to right) to see how it looks.  My guess it will be really disruptive on screen 1 when dragging, but if it isn't a pain to test and see, I'd like to see how it feels when interacting with the sim.

**Comment by jonathanolson** [comment]
Reduced factor font size (currently for all screens) to fit:
![area-model-factor-font](https://cloud.githubusercontent.com/assets/480878/26028233/a00f414c-37d9-11e7-99fb-5877d3e90430.PNG)

**Comment by jonathanolson** [comment]
I started with an implementation that has minimum sizes (helpful for the line-by-line view and having it look nice on the non-generic screens).

Check http://www.colorado.edu/physics/phet/dev/html/area-model-multiplication/1.0.0-dev.4/area-model-multiplication_en.html to see how that behavior feels?

**Comment by amyh-phet** [comment]
Behavior seems reasonable as I interact with sim.  Size does jump as I change number of partitions, but this gives a good cue that I've now changed how the area is calculated, resulting in a different display in the calculation panel.

**Comment by jonathanolson** [comment]
Merged branch into master.

Keeping open to discuss how to handle arrows for the partial products/factors display. Thoughts/mockups?

**Comment by amyh-phet** [comment]
Currently working on mockups for overlay we discussed in design meeting last week.  I'm assuming this is for issues with Screen 1?  Would you like mockups here or in the design doc?

**Comment by jonathanolson** [comment]
> I'm assuming this is for issues with Screen 1?

Yes, and the decimals screen (presumably a mock-up of one will work for the other, no need to duplicate work).

> Would you like mockups here or in the design doc?

Here would be most convenient for me, but the design doc would be fine also.

**Comment by amyh-phet** [comment]
Here's what I have so far using only arrows and no overlay.
![20x20_2x2_arrows](https://cloud.githubusercontent.com/assets/13650180/26080190/a325d6b6-3982-11e7-91a7-151460c62f96.png)
![20x20_display_arrows](https://cloud.githubusercontent.com/assets/13650180/26080192/a32695ec-3982-11e7-90a6-429c4fcb7d73.png)
![100x100_21x5_edgecase](https://cloud.githubusercontent.com/assets/13650180/26080191/a326461e-3982-11e7-87f8-55fda889f55f.png)
![100x100_edge_case_5x31](https://cloud.githubusercontent.com/assets/13650180/26080189/a32597aa-3982-11e7-99e6-1355dd19731c.png)

**Comment by jonathanolson** [comment]
Best attempt made to prevent overlap of labels. Also adjusts positioning so it won't run over the dimension line labels on the left.

@amyh-phet can you experiment with this to see if there's anything else I can do?

**Comment by amyh-phet** [comment]
@jonathanolson    I think we've dealt with all parts of this issue.  Feel free to close or comment if more needs to be done.
