### ISSUE TITLE
Parameter types for wrapObject/wrapOrientationPair, etc

### ISSUE THREAD

**Issue by samreid** [phetsims/area-model-common#112]
During the review https://github.com/phetsims/area-model-common/issues/99 I noted methods like: `wrapObject` and `wrapOrientationPair`.  While passing a map function is fully general, it seems like for the case of these methods in particular it would be sufficient to supply a string for the getter.  For instance, we could rewrite:

```js
    // @public {Property.<number>}
    this.coordinateRangeMaxProperty = this.wrapObject( function( area ) {
      return area.coordinateRangeMax;
    } );

    // @public {Property.<boolean>}
    this.allowExponentsProperty = this.wrapObject( function( area ) {
      return area.allowExponents;
    } );
```

like

```js
    // @public {Property.<number>}
    this.coordinateRangeMaxProperty = this.wrapObject( 'coordinateRangeMax' );

    // @public {Property.<boolean>}
    this.allowExponentsProperty = this.wrapObject( 'allowExponents' );
```

I'm not advocating for the latter, but wanted to discuss it.  Have you considered that strategy?  Is it any clearer?  Is it better to go with the map functions since they are more general?  There are 11 occurrences of `wrapObject`, for example (and more for the other wraps).  I wouldn't advocate to change to the string variant based solely on number of lines of code, but wanted to get your thoughts about it.

For the sake of completeness, it looks like lodash has a `_.property` method that could work with the function declarations like this:

```js
    // @public {Property.<number>}
    this.coordinateRangeMaxProperty = this.wrapObject( _.property('coordinateRangeMax') );

    // @public {Property.<boolean>}
    this.allowExponentsProperty = this.wrapObject( _.property('allowExponents' ));
```

**Comment by samreid** [comment]
> @samreid changed the title from Are the repos set up like we like them? to Parameter types for wrapObject/wrapOrientationPair, etc just now

Sorry about the bad title, it was leftover from old notes and can be disregarded.

**Comment by jonathanolson** [comment]
> Have you considered that strategy? Is it any clearer?

I've thought about it, and in general I think it's potentially nice to be able to use `_.property`. I've used it with DynamicProperty, and it's worked well. However I think a lot of that comes from us not being able to use arrow functions. And in the DynamicProperty case, I like being able to specify a string OR a function.

In this case, it isn't common code, I didn't know about how general it would have to be up front, so I just went with the simple general case. I'm happy to refactor this to use strings instead.

In general, I'm curious whether using strings or `_.property` messes with Intellij (e.g. if something's only usage is through that, will it show up as unused, etc.?)

Thoughts?

**Comment by jonathanolson** [comment]
Would you recommend having the methods take strings (and using _.property in those), or just using _.property and leaving the parameter as a function?

**Comment by samreid** [comment]
For now, let's use _.property and require a function argument.  Then we can see how that looks (I think it sounds promising).

**Comment by jonathanolson** [comment]
Done above.

There are a lot of other usages that COULD use _.property (DerivedProperty, etc.). Should those also be changed, or left as-is for now?

**Comment by samreid** [comment]
> There are a lot of other usages that COULD use _.property (DerivedProperty, etc.). Should those also be changed, or left as-is for now?

Can you refer me to one or two examples?

**Comment by jonathanolson** [comment]
GameAreaDisplay line 76? Actually that may be the only case.

**Comment by samreid** [comment]
I think I see another one on line 44 of that same file.  No preference about those, they can remain as they are or you can change them.  By the way, AreaDisplay looks a lot clearer now.

**Comment by jonathanolson** [comment]
> I think I see another one on line 44 of that same file.

Changed. Feel free to leave review notes for any you see that can be simplified like that.

**Comment by samreid** [comment]
Looks good, thanks.  I'll close the issue, but if we discover other spots using that pattern we can convert them to _.property if we wish.
