### ISSUE TITLE
The area selection handle pops to different locations

### ISSUE THREAD

**Issue by samreid** [phetsims/area-model-common#113]
Discovered in #99, Depending on where it was dropped last, the area selection handle can "pop" to different locations on mouse press.  Then on mouse move, it snaps to the cursor location. It can jump maybe 20+ pixels sometimes.  This may not be a severe UX problem, but I thought I'd bring it up in case it reveals some underlying flaw or code issue.
![tapping2](https://user-images.githubusercontent.com/679486/38772938-5adc2fa2-3fff-11e8-875f-e289bbd90597.gif)

**Comment by jonathanolson** [comment]
Wasn't updating the position if there was a press without a drag (so it used the last offset from the previous drag). Should be fixed, can you verify?

**Comment by phet-steele** [comment]
@samreid I got your back! Verified!

**Comment by phet-steele** [comment]
Hold on....I thought this was a nice feature, but now I'm second guessing....stand by.

**Comment by phet-steele** [comment]
New issue in #133.
