### ISSUE TITLE
Clicking on the scorebar returns to the main screen

### ISSUE THREAD

**Issue by samreid** [phetsims/area-model-common#115]
Discovered in #99. I was surprised to see that clicking on the stars in the http://localhost/area-model-algebra/area-model-algebra_en.html?brand=phet&ea game screen scoreboard node returned to the level selection screen.  There is no mouse hand for that.  Is that behavior by design?  If so, why?  And if so, shouldn't the mouse be a hand?

**Comment by samreid** [comment]
Update: sometimes the cursor becomes a hand over the scorebar node and sometimes it doesn't.  It seems if you make circles of a diameter just larger than the scorebar node, it increases the odds of having an arrow.

**Comment by jonathanolson** [comment]
Was noted in the comment https://github.com/phetsims/area-model-common/issues/80#issuecomment-379919660, pending on feedback from @amanda-phet.

**Comment by amanda-phet** [comment]
This is behaving normally now.
