### ISSUE TITLE
Should we implement ?showAnswers?

### ISSUE THREAD

**Issue by samreid** [phetsims/area-model-common#116]
Discovered in #99. Several PhET games support the ?showAnswers query parameters to facilitate game testing.  Should we support that for this sim as well?  There is also talk about standardizing that so we can disable it during build, see https://github.com/phetsims/joist/issues/406#issuecomment-380205752

**Comment by samreid** [comment]
Looks great, thanks!

**Comment by phet-steele** [comment]
Just as I was hoping, thanks @jonathanolson!
