### ISSUE TITLE
replace ProgressIndicator with ScoreDisplayStars

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/area-model-common#118]
`ProgressIndicator` is deprecated per #59. It should be replaced by `ScoreDisplayStars`.

Then please delete `ProgressIndicator`.

**Comment by jonathanolson** [comment]
The only usage is in the code that will be replaced by the common vegas bar code.

**Comment by jonathanolson** [comment]
This happened when we started using FiniteStatusBar, closing.

**Comment by pixelzoom** [comment]
Reopening. `ProgressIndicator` still exists.

**Comment by jonathanolson** [comment]
Sorry, totally missed that part somehow. Will delete.

**Comment by jonathanolson** [comment]
Done, sorry about that. Closing.
