### ISSUE TITLE
iPad2 performance review

### ISSUE THREAD

**Issue by samreid** [phetsims/area-model-common#119]
I was asked to test performance on iPad2, here is what I observed:

Area Model Algebra (built), 
time to launch
21 seconds
26 seconds

Crashed on 3rd load "a problem occurred with this webpage so it was reloaded"
Refresh time:
22 seconds

Dragging the lollipop on screen 1 (Area Model Algebra - built): 10fps
Dragging the red partition: 20fps
Dragging the lollipop with all indicators turned on: 4fps

Game performance seems reasonable--I didn't try the reward node, though.

@ariel-phet can you please recommend how to proceed regarding iPad2 performance and startup time?

**Comment by jonathanolson** [comment]
> I didn't try the reward node, though.

IIRC, there's a large delay before the RewardNode actually shows up.

**Comment by ariel-phet** [comment]
@samreid in this particular case, as long as performance is good on later iPads, I do not think anything should be done.

Although the performance is most definitely sluggish on iPad2 with all indicators active, for this particular sim, dragging things quickly back and forth is not really pedagogically productive. Given the dwindling popularity of the iPad2 and the nature of the sim, I am inclined to leave performance as is on this platform.

Tagging @phet-steele so he is aware for QA

**Comment by jonathanolson** [comment]
@ariel-phet since this issue was fine enough for the initial release, should something be done now or can it potentially be closed?

**Comment by ariel-phet** [comment]
Yes, fine to close. Closing
