### ISSUE TITLE
Review of area calculation lines

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/area-model-common#12]
http://www.colorado.edu/physics/phet/dev/html/area-model-multiplication/1.0.0-dev.3/area-model-multiplication_en.html should be (mostly) feature complete, so I was wondering if you could check the area-calculation lines to make sure they look as expected and that the proper lines are shown.

I ended up with the following lines and visibilities:

- "totals" line, always visible: shows the product of simplified width and height sums.
- "expanded" line, visible if different from the totals line: expands the width and height to the ordered sum of partitions
- "distribution" line, visible if there is more than one partition for either width or height: distributes the terms
- "multiplied" line, visible if the distribution line is visible AND it is different from the final total line: multiplies width/height terms together, wrapping negatives in parentheses
- "ordered" line, visible if the multiplied line is visible AND it needs reordering (but hidden if the ordered line would be the same as the total sum line, counting "wrapped in parentheses" as different): Reorders the "multiplied" line so that exponents are in order.
- "minuses" line, visible if the multiplied line is visible, we're in the 3rd screen, there is a negative term, AND the ordered terms is not the same as the total sum line: unwraps negative values, uses '-' between expressions where relevant.
- "total sum" line, always visible: shows the simplified sum of the totajl area.

If it was confusing in English, the (current) code shows the logic slightly better:
```js
var needsExpansion = !horizontalTermList.equals( horizontalPolynomial ) || !verticalTermList.equals( verticalPolynomial );
var needsDistribution = horizontalTermList.terms.length !== 1 || verticalTermList.terms.length !== 1;
var needsMultiplied = needsDistribution && !multipliedTermList.equals( totalPolynomial );
var needsOrdered = needsMultiplied && !orderedTermList.equals( multipliedTermList ) &&
                   !( orderedTermList.equals( totalPolynomial ) && ( !this.allowPowers || !orderedTermList.hasNegativeTerm() ) );
var needsMinuses = needsMultiplied && this.allowPowers && orderedTermList.hasNegativeTerm() && !orderedTermList.equals( totalPolynomial );
```

Definitely let me know if anything here seems out-of-place (particularly if there seems to be a "missing" or "duplicate" line ever).

**Comment by amyh-phet** [comment]
As I play with the sim, I'm wondering if we need to rearrange what students input on model on Screen 3.  For example, if a student enters 3 in the first partition and -x in the second partition, -x+3 is displayed in the problem panel and on the dimension line.  In discussing with @amanda-phet, we should consider displaying 3-x on the dimension line and in the Problem panel.  This would eliminate a need to add an additional line where the order of variables is displayed differently on the variables screen.   

Adding this item to discussion items for design meeting on Thursday.

For now, let's leave items as they are.

**Comment by jonathanolson** [comment]
Would a dev version (off of a branch) help to compare the potential change?

Also note that the Problem panel combines/sorts factors, so "3-x" should be displayed on it currently. Only the extra calculation line would be removed, and the top calculation like would show the simplification?

I'd like to know whether this is just sorting or if it includes further simplification. A good example would be: what happens to `x, 5, -x`. Does it get simplified for the first calculation line as `5`? 

Personally, I feel uncomfortable (currently disagree) with simplifying the calculation process for that, since it breaks the "distribute into partitioned areas, then calculate" feel. Instead of `x, 5, -x` as the three partitions (which are shown visually), it remaps it in the calculation into a single partition (`5`). There would be no mapping from visual partitioned areas to distributed terms in the calculation.

I'd advocate either keeping or removing the "extra" line and leaving the other parts the same. I don't have a strong feeling on whether the top line of the calculation should stay as-is, or should be rearranged to match the order of the user's partitions.

**Comment by amyh-phet** [comment]
So let me do a better job of clarifying what I meant as I agree that simplifying the calculation process too much will cause a break down in the mapping of the model to the calculation panel.

In dev 4, I can build this problem:
![calculation_question_dev4](https://cloud.githubusercontent.com/assets/13650180/26081519/67b1f71c-3988-11e7-95fe-7cf832282d26.png)

I think that it might be more clear to students if the problem and dimension lines displayed what they entered rather than simplifying.  Here's mockup of what I'm proposing the Problem panel, dimension lines, and calculation display would look like:
![calculation_panel_question](https://cloud.githubusercontent.com/assets/13650180/26081475/2143e236-3988-11e7-892e-8c24edc71e23.png)

In the example you gave above, I can build this in dev 4:
![calculation_panel_question_dev4_2x3](https://cloud.githubusercontent.com/assets/13650180/26082083/271c3dea-398b-11e7-8f37-2fe75dfec9fd.png)



I'm thinking this behavior seems more natural.
![calculation_panel_question_2x3](https://cloud.githubusercontent.com/assets/13650180/26082162/a39de5a8-398b-11e7-9e8d-f1f9bbd8c87a.png)

@amanda-phet     Any thoughts?

**Comment by amanda-phet** [comment]
I agree with @amyh-phet . While we typically write expressions in order of degree of exponent, there are times when an expression like 3-x is appropriate (such as a word problem where a length of 3 is reduced by some amount). We also don't want to make students think that it's wrong to multiply a binomial like 3-x. 

In the second example, a teacher could point out that in the area model 3x, -3x, and -x^2, x^2 should cancel when finding the total area, and point out that the side length of x-5-x is the problem... it would be simpler to just write 5 there, change it, and see how the calculation is greatly simplified. It seems strange to me to see 5 as the side length of the model and yet see such complicated calculations.

**Comment by jonathanolson** [comment]
I don't quite remember if this was fully decided at the design meeting; should the changes above be made, or is it pending on any further decisions?

**Comment by amyh-phet** [comment]
We agreed that changes should be made.

**Comment by jonathanolson** [comment]
Change made in master, let me know if it looks as expected.

**Comment by amyh-phet** [comment]
Looks good  Behaving as expected

**Comment by amyh-phet** [comment]
Looks like this is also finished, so closing.
