### ISSUE TITLE
Smiley face overlaps with the keypad

### ISSUE THREAD

**Issue by phet-steele** [phetsims/area-model-common#120]
The smiley face overlaps with the keypad after two failed attempts:

<img width="773" alt="screen shot 2018-04-16 at 2 05 51 pm" src="https://user-images.githubusercontent.com/5863899/38832603-495c5f90-4180-11e8-9ac1-14fd76a951d1.png">

To repro in either AMA or AMM:
1. Fail two times on a challenge requiring a keypad, but do not press "Show Answer".
2. Edit a field that will bring up the keypad.

I see three options to address this:

1. Do not allow fields to be edited after two failed attempts, therefore not allowing the keypad to be accessed.
2. Move the smiley face to a new location.
3. Remove the smiley face when a field is edited.

(3) seems easiest and is consistent with how the smiley face behaves after one failed attempt (it will hide when editing after a first attempt).

Seen on master 4/16, noon? macOS 10.13.3 Chrome.

**Comment by jonathanolson** [comment]
@amanda-phet, what is the preferred solution?

**Comment by amanda-phet** [comment]
discussion on 4/16/18 

2. move smiley back to old location centered under "submit" button.

**Comment by jonathanolson** [comment]
Moved the smiley, can you see if this works well?

**Comment by amanda-phet** [comment]
Working for me.

**Comment by phet-steele** [comment]
👍
