### ISSUE TITLE
Move common/enum/*Choice.js to common/model

### ISSUE THREAD

**Issue by samreid** [phetsims/area-model-common#121]
It seems odd that js/common/ has model/ view/ and enum/, especially since those enums take part in the model.  I recommend moving those two files to common/model/AreaCalculationChoice.js and common/model/PartialProductsChoice.js.  If there were more files (or they didn't end in *Choice.js) then common/model/enum/ may be warranted, but I don't think it's warranted in this case.

From #99

**Comment by jonathanolson** [comment]
There aren't that many across all places. I thought the separation might be helpful, but I'd be fine moving everything under enum (common, generic, proportional and game) to under model?

Notably proportiona/enum has one file.

Consistency of having them either all under enum/ or all under model (or view, if view-specific) sounds helpful.

Thoughts?

**Comment by samreid** [comment]
For each of the js/ subdirectories, I recommend moving the js/{{subdirectory}}/enum files to the corresponding js/{{subdirectory}}/model or js/{{subdirectory}}/view directory as appropriate.  If it is too much clutter (say, >3 enums that don't all end with Choice or Type), then you can additionally create js/{{subdirectory}}/(model|view)/enum.

**Comment by jonathanolson** [comment]
All of the enumerations were used in the model, so I moved all of them to their respective model directories in the above commit.

**Comment by samreid** [comment]
Change set looks good, thanks!
