### ISSUE TITLE
Discussion about Pooling nodes

### ISSUE THREAD

**Issue by samreid** [phetsims/area-model-common#122]
From #99.  This was a review comment in TermText.js but I wanted to promote it to an issue to foster and accelerate discussion.

> For poolable types, it would be nice to describe why pooling is valuable.  Are these created lots of times?  Does performance suffer on iPad if not pooled, etc?  Generally, pooling adds complexity so it would be good to document why that complexity is warranted.

I noticed even the QuestionMark which is just a Text('?') is pooled.  Perhaps document it here in the issue and copy it to the implementation-notes.md.

Also, is pooling superior to using scenery DAG?

**Comment by jonathanolson** [comment]
> Also, is pooling superior to using scenery DAG?

In this particular case, I didn't want to have to create "wrapper" nodes on every update. I could have also used DAG features for the question mark (but not things like TermText), where the wrapper nodes would be pooled.

> it would be nice to describe why pooling is valuable.

I'll add more info in documentation, but basically it was creating OODLES of nodes every frame, which had a significant performance penalty (the GC was dwarfed just by the CPU cost of creating a ton of nodes every frame). It significantly improved performance.

> Perhaps document it here in the issue and copy it to the implementation-notes.md.

Will do.

**Comment by jonathanolson** [comment]
Noted things about pooling in the implementation notes. Anything else to do?

**Comment by samreid** [comment]
That makes sense, thanks, closing.
