### ISSUE TITLE
EditableProperty => Entry

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/area-model-common#123]
Entry will have `valueProperty` (which is the Property part of EditableProperty) with composition instead of inheritance. The naming also makes more sense with https://github.com/phetsims/area-model-common/issues/117.

Then many things that are confusing (properties of properties) turn to things like properties of entries.

**Comment by jonathanolson** [comment]
Implemented with the commit above (which could use some inspection).

Since it was slightly trickier in some spots, I ran a 2000-snapshot comparison on both sims with games (passed).

**Comment by samreid** [comment]
Entry is looking much nicer, thanks!  Also, what is a 2000-snapshot comparison and how did you run it?

**Comment by jonathanolson** [comment]
http://localhost/aqua/html/snapshot-comparison.html?sims=area-model-algebra,area-model-multiplication&numFrames=2000. I usually load it while on the "old/desired" SHA, wait for it to finish, check out master, then press the "Start Snapshot" button to start another snapshot. When done, the SHAs were the same (so pixel-identical). If they weren't, clicking on the bold SHA text will display all frames that differed (similar to Scenery unit tests).

Notes:

- I wouldn't normally view deltas with 2000 frames, that's a lot. Usually if there is a difference, I tweak the sim size and frames to make it easier to see if needed (see query params in snapshot-comparison.js)
- It's a temporary UI and setup. Will be cleaned up, issue tracking is https://github.com/phetsims/aqua/issues/22.

**Comment by samreid** [comment]
Sounds great, and changes look great too, nice work.  Closing.
