### ISSUE TITLE
Bad maxWidth on game completion panel

### ISSUE THREAD

**Issue by phet-steele** [phetsims/area-model-common#126]
With `?stringTest=long`. I will say that with `?stringTest=double`, you can hardly tell there is an issue.

<img width="1347" alt="screen shot 2018-04-18 at 12 19 03 pm" src="https://user-images.githubusercontent.com/5863899/38950484-e72f8cd2-4302-11e8-98bb-dfcc09500f6c.png">

Seen on master (10 AM 4/18) macOS 10.13.4 Chrome.

**Comment by jonathanolson** [comment]
@pixelzoom, should I be applying a maxWidth to the entire LevelCompletedNode? Or should LevelCompletedNode apply maximum widths itself?

**Comment by pixelzoom** [comment]
What's the issue?  From the screenshot it looks like it fits inside layoutBounds.

**Comment by phet-steele** [comment]
@pixelzoom here is ideal width:

<img width="1568" alt="screen shot 2018-04-18 at 4 11 56 pm" src="https://user-images.githubusercontent.com/5863899/38960834-40c2005c-4323-11e8-844c-dc2f3aa12aae.png">

**Comment by jonathanolson** [comment]
@pixelzoom I see no indication that there is a fixed size. Objections for me to add `contentMaxWidth` as an option to VEGAS/LevelCompletedNode, which is applied independently to each text (and the rest of it too like the button and score display?)

**Comment by pixelzoom** [comment]
I hadn't looked at the code, and your screenshot didn't demonstrate a problem.

No objections to adding `contentMaxWidth`.

**Comment by jonathanolson** [comment]
Done in master. @phet-steele can you verify?

**Comment by phet-steele** [comment]
Looking good 👍
