### ISSUE TITLE
Game memory leak

### ISSUE THREAD

**Issue by phet-steele** [phetsims/area-model-common#128]
_**I've only tried AMM so far, not AMA.**_

Running a local build of AMM with `?screens=3`. The game was fully completed then reset, then fully completed and reset again.

| | |
| --- | --- |
| Start | 33.2 MB |
| All levels to 6* | 41.1 MB |
| Reset All | 40.9 MB |
| All levels back to 6* | 45.9 MB |
| Reset All | 45.6 MB |

This data would tell me that, after multiple repeated attempts of the game, we would eventually run out of memory. @jonathanolson let me know if this test was kosher and has any merit at all.

Seen on macOS 10.13.4 Chrome, master (3 PM, 4/18).

**Comment by jonathanolson** [comment]
Hmm, looks like RewardNode is definitely leaking memory (repeated your process a few more times to confirm).

**Comment by jonathanolson** [comment]
Fixed the main leak, checking about what may be a smaller leak.

**Comment by jonathanolson** [comment]
Automated with delays (to make sure the rewards show):

```s
var model = phet.joist.sim.screens[2].model;

var actions = [];

for ( let i = 0; i < 10; i++ ) {
  for ( let levelIndex = 0; levelIndex < 6; levelIndex++ ) {
    actions.push( function() { model.selectLevel( model.levels[ levelIndex ] ); } );
    for ( let challengeIndex = 0; challengeIndex < 6; challengeIndex++ ) {
      actions.push( function() {
        model.cheat();
        model.check();
        model.next();
      } );
    }
    actions.push( function() { model.moveToLevelSelection(); } );
  }
  actions.push( function() { model.reset(); } );
}

var idx = 0;
(function act() {
  actions[ idx++ ]();

  if ( idx === actions.length ) { idx = 0; }
  setTimeout( act, 500 );
})();
```

It looks like it is leaking at most 3MB/hour. I believe at this level, it shouldn't block the "initial" publication.

**Comment by jonathanolson** [comment]
Things are to a satisfactory level (there potentially exists a leak but it is in the noise).
