### ISSUE TITLE
Leading negative is lost on calculation step (Variables screen)

### ISSUE THREAD

**Issue by phet-steele** [phetsims/area-model-common#129]
@jonathanolson I'm only seeing this on the Variables screen. I believe that screen is the only place where this step in the calculation panel is visible.

Set up this model on 3x3:
<img width="858" alt="screen shot 2018-04-19 at 12 38 31 pm" src="https://user-images.githubusercontent.com/5863899/39011612-2c6eccdc-43cf-11e8-8424-0ed37ffbcdd9.png">

Notice in the calculation panel, on the step before the last, the leading negative is lost:
<img width="558" alt="screen shot 2018-04-19 at 12 34 16 pm" src="https://user-images.githubusercontent.com/5863899/39011611-2c5bae72-43cf-11e8-9e0a-d018534c9f89.png">

Seen on master (noon, 4/19) macOS 10.13.4 Chrome.

**Comment by jonathanolson** [comment]
Yikes, will fix.

**Comment by jonathanolson** [comment]
Fixed in the above commit.

**Comment by phet-steele** [comment]
👍
