### ISSUE TITLE
Area handle snaps to new dimensions without dragging

### ISSUE THREAD

**Issue by phet-steele** [phetsims/area-model-common#133]
The changes in #113 have revealed a (in my opinion annoying) problem.

If you are using a model with many small subdivisions, ie. the 3x3 in area-model-decimals, clicking on the edges of the lollipop will jump the handle and cause the area to change. In the below gif, I'm only clicking, not dragging, and the handle is snapping to different dimensions:

![amd01](https://user-images.githubusercontent.com/5863899/39064106-7e08b2ae-448a-11e8-8342-957df5173fea.gif)

@jonathanolson I made this a new issue because it still could happen BEFORE changes in #113, but was much harder to do. Also labeling as polish since I don't think this is severe.

**Comment by samreid** [comment]
I agree with @phet-steele that grabbing the handle should not change the model value--ideally the sim would be able to track the correct relative drag position (on the drag handle) instead of jumping it to the center on grab.

**Comment by phet-steele** [comment]
Feels beautiful.
