### ISSUE TITLE
[IE11] Incompatible usage of Array.find()

### ISSUE THREAD

**Issue by phet-steele** [phetsims/area-model-common#137]
In `CalculationLinesNode.js` line 212, there is an incorrect usage of ".find". Should be "_.find()".

Could be more elsewhere, this is just the one I noticed first.

```js
getActiveLine: function() {
      var activeLine = this.calculationLinesProperty.value.find( function( line ) { ... } ) || null;
... }
```
This is incompatible with IE11. For phetsims/QA/issues/113.

**Comment by jonathanolson** [comment]
Should be fixed with the above commit. I'll be cherry-picking in, wait for confirmation in the next RCs.

**Comment by phet-steele** [comment]
Fixed.
