### ISSUE TITLE
Parentheses in MathSymbols

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/area-model-common#140]
They are used a lot in this sim, and it was brought up in review: "what is the criteria for something belonging in MathSymbols?"

I could see the potential where we may try to switch symbols, but it may also be pretty unlikely. Thoughts?

**Comment by pixelzoom** [comment]
Do you mean like this, in Area Model Introduction ?

![screenshot_595](https://user-images.githubusercontent.com/3046552/39278685-c53b9436-48b1-11e8-93f8-4508a5da205e.png)

I'd doubt that parens will ever be replaced by something else.  But if you're really concerned, ask one of the math designers.

**Comment by jonathanolson** [comment]
@amanda-phet, will parentheses ever potentially be replaced?

**Comment by amanda-phet** [comment]
I'm not sure I understand the question... the parentheses look the way they should, and I would like all future uses of parentheses to look this way. If we want them in MathSymbols, it would be mainly for consistency. I don't think we will replace parentheses with other symbols or representations.

**Comment by jonathanolson** [comment]
Sounds good, closing.
