### ISSUE TITLE
[IE11] Number.parseInt() should not be used

### ISSUE THREAD

**Issue by phet-steele** [phetsims/area-model-common#141]
Number.parseInt() is being used at least here (and maybe elsewhere): https://github.com/phetsims/area-model-common/blob/master/js/generic/view/TermAccumulator.js#L90

This is incompatible with IE11. For phetsims/QA/issues/113.

**Comment by jonathanolson** [comment]
Should be fixed (and is on branches)

**Comment by phet-steele** [comment]
👍
