### ISSUE TITLE
"Enter" button should be yellow

### ISSUE THREAD

**Issue by phet-steele** [phetsims/area-model-common#142]
@amanda-phet requested that the "Enter" button in the keypads be yellow.

For phetsims/QA/issues/113.

**Comment by amanda-phet** [comment]
While reviewing Amy's interview notes today I noticed a student or two had trouble clicking enter, and while playing the game today I realized the enter button was not yellow (but it is in Unit Rates and I think it works well in that sim). So, I thought it would be a good change here too.

**Comment by jonathanolson** [comment]
Done (and put into the release branches).

**Comment by amanda-phet** [comment]
Looking great to me now! Thanks so much.
