### ISSUE TITLE
Performance recheck after a11y is added

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/area-model-common#146]
Since this sim barely squeaked by performance-wise, I don't want to forget checking this before we move to rc.1.1

**Comment by jonathanolson** [comment]
Notably the partial product innerContent update may be done on every change, and could potentially be (somehow?) batched. Other performance considerations may also exist.

**Comment by jonathanolson** [comment]
@ariel-phet would this be good to have checked by QA before a full RC for 1.1?

**Comment by ariel-phet** [comment]
Looks like performance was fine in latest RC test. Closing
