### ISSUE TITLE
Should the Keypad readout change to indicate maximum width?

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/area-model-common#15]
Examples of appearance:
![screen shot 2017-05-14 at 12 23 16 am](https://cloud.githubusercontent.com/assets/480878/26031745/b2818602-383b-11e7-983c-c816ae4efe7c.png)
![screen shot 2017-05-14 at 12 23 25 am](https://cloud.githubusercontent.com/assets/480878/26031746/b78cd174-383b-11e7-8aa3-06d42fd61e35.png)
![screen shot 2017-05-14 at 12 23 32 am](https://cloud.githubusercontent.com/assets/480878/26031747/bcf3c960-383b-11e7-9be8-09a2ceb4be35.png)

Alternatively I can have the readout take up a larger width.

**Comment by amyh-phet** [comment]
I like having the keypad readout resize if possible for an additional cue that number entry is constrained for each partitioned area.

**Comment by jonathanolson** [comment]
Already as implemented, closing.
