### ISSUE TITLE
Make sure NumberPicker readouts are as desired

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/area-model-common#164]
Motivated by #155 and from https://github.com/phetsims/sun/issues/356. The NumberPickers are behaving correctly for a11y, but we want to make sure that the sim specific units/readout is as desired. Right now the readout is just "0.5" or the input value. Does a user need to  hear anything else as the value changes?

**Comment by amanda-phet** [comment]
I believe the readout should just be the value, no units.

**Comment by jessegreenberg** [comment]
OK, I think that means we can close this.
