### ISSUE TITLE
'grunt published-README' was not run in 1.0 branches

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/area-model-common#165]
The 1.0 branches of the Area Model sims still indicate that the sim is unpublished.

The master checklist for sims says:

> - [ ] README.md updated using `grunt published-readme` (in master and release branch)

**Comment by pixelzoom** [comment]
This appears to be a problem with `grunt production`.  It runs `grunt published-README` in master, but not in the release branch.

**Comment by jonathanolson** [comment]
This was handled as part of https://github.com/phetsims/chipper/issues/698, closing.
