### ISSUE TITLE
Overlapping Partial Products Boxes

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/area-model-common#166]
**Test device:**
Dell Laptop
**Operating System:**
Windows 10
**Browser:**
Chrome  68.0.3440.75
**Problem description:**
For phetsims/QA/issues/157
On parts of the sim where it is possible to control the red and blue dividing lines and to add partial product dialog boxes it is possible to get these boxes to overlap quite a bit.
**Steps to reproduce:**
(This can be done in many of the sims, this is just one way to do it)
1. Open Area Models Decimal
2. Choose the 2x2 button
3. Shrink the dimensions to .2 x .2
4. Use the red and blue dividing lines to create four .1x.1 partial products
5. Select the axb partial products button

**Screenshots:**
![crowded](https://user-images.githubusercontent.com/41024075/43350257-003cbdf8-91c3-11e8-8ffb-b768bf8f1259.PNG)

Troubleshooting information (do not edit):
<details>
Name: ‪Area Model Decimals‬
URL: https://phet-dev.colorado.edu/html/area-model-decimals/1.1.0-dev.1/phet/area-model-decimals_en_phet.html
Version: 1.1.0-dev.1 2018-07-26 17:22:15 UTC
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/68.0.3440.75 Safari/537.36
Language: en-US
Window: 1536x737
Pixel Ratio: 2.5/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 30 uniform: 4096
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {"area-model-common":{"sha":"796b9997","branch":"master"},"area-model-decimals":{"sha":"b2584dea","branch":"master"},"assert":{"sha":"928741cf","branch":"master"},"axon":{"sha":"0353caeb","branch":"master"},"brand":{"sha":"89d28f63","branch":"master"},"chipper":{"sha":"688f8993","branch":"master"},"dot":{"sha":"54f7fb7d","branch":"master"},"joist":{"sha":"4ac76566","branch":"master"},"kite":{"sha":"6bd3398c","branch":"master"},"phet-core":{"sha":"9c242cdc","branch":"master"},"phet-io":{"sha":"ca17e38a","branch":"master"},"phet-io-wrapper-classroom-activity":{"sha":"6091622c","branch":"master"},"phet-io-wrapper-hookes-law-energy":{"sha":"51f1f524","branch":"master"},"phet-io-wrapper-lab-book":{"sha":"3d0ed29f","branch":"master"},"phet-io-wrappers":{"sha":"45a360ca","branch":"master"},"phetcommon":{"sha":"d4196e1e","branch":"master"},"query-string-machine":{"sha":"4178d27a","branch":"master"},"scenery":{"sha":"5347f0ef","branch":"master"},"scenery-phet":{"sha":"412b369c","branch":"master"},"sherpa":{"sha":"79fb5b8c","branch":"master"},"sun":{"sha":"6a383379","branch":"master"},"tambo":{"sha":"93107274","branch":"master"},"tandem":{"sha":"0c6d2f43","branch":"master"},"twixt":{"sha":"a73e9257","branch":"master"},"vegas":{"sha":"6b3c902c","branch":"master"},"vibe":{"sha":"960a83ef","branch":"master"}}
</details>

**Comment by amanda-phet** [comment]
Yes, we are aware of the overlapping, and it was a design compromise for this particular case.
