### ISSUE TITLE
Axon Properties should end in `Property` suffix

### ISSUE THREAD

**Issue by samreid** [phetsims/area-model-common#169]
Discovered during https://github.com/phetsims/tambo/issues/46, I saw that Area Model Common had a few axon Properties that didn't end with a Property suffix:

AreaModelCommonModel.js
```js
    // @public {Property.<boolean>}
    this.factorsBoxExpanded = new BooleanProperty( true );

    // @public {Property.<boolean>}
    this.areaBoxExpanded = new BooleanProperty( options.initialAreaBoxExpanded );
```

I'm not sure whether or not there are others.  Generally it is best if axon Properties end in the suffix `Property`.  Also, PhET-iO tandems require a `Property` suffix for Property types.

**Comment by jonathanolson** [comment]
Whoops, sorry!

Should be fixed in the above commit. I checked for `= new Property`, `= new BooleanProperty`, and `= new NumberProperty` and didn't see any other cases.

Can you verify?

**Comment by samreid** [comment]
Looks great, thanks @jonathanolson!
