### ISSUE TITLE
Reset all button pointer area

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/area-model-common#170]
For https://github.com/phetsims/QA/issues/231
Per @ariel-phet the touch pointer area of the reset all button does not always need to be larger.  As seen here, the pointer area might be getting a bit close to other buttons and it might be a good idea to take a second look.
![tooclose](https://user-images.githubusercontent.com/41024075/49754640-de8cad00-fc73-11e8-837f-bc3719425777.PNG)

**Comment by jonathanolson** [comment]
@ariel-phet I'm not sure I understand. Is there an advantage to having an "unclickable" area in-between? To me it is generally an advantage, when two buttons are somewhat close, for any click between them to register on one of them.

**Comment by ariel-phet** [comment]
Related to https://github.com/phetsims/friction/issues/65. Going to make a comment there, and I think we will make a project-wide default

**Comment by ariel-phet** [comment]
Full comments here https://github.com/phetsims/friction/issues/65#issuecomment-446296242 the relevant snippet copied for convenience

> 
@samreid can you change the default touch dilation area of ResetAllButton to match what was done in Atomic Interactions/SOMB. That should work project-wide and strike the balances we are looking for in the UX.

**Comment by samreid** [comment]
This sim was checked off as part of https://github.com/phetsims/tasks/issues/985 and looks pretty good:

![image](https://user-images.githubusercontent.com/679486/52251382-c1620c80-28b9-11e9-8e24-f0522b1acf54.png)

Closing.
