### ISSUE TITLE
Double Pointer Area

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/area-model-common#171]
For https://github.com/phetsims/QA/issues/231
When looking at the touch pointer areas for the number inputs there seem to be two.  I have not noted any problems that arise from this, but it seems odd to me.
![doublepointarea](https://user-images.githubusercontent.com/41024075/49754950-bf424f80-fc74-11e8-8047-c52698f46a46.PNG)

**Comment by jonathanolson** [comment]
This is expected, since I'm also setting the touch area for a composite component (essentially).

**Comment by KatieWoe** [comment]
In that case, closing
