### ISSUE TITLE
Line in front of drag handle

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/area-model-common#172]
For https://github.com/phetsims/QA/issues/231.
When the drag handle is at the edge of the graph the outer lines seem to be in front of it, which seems odd to me.  This is how it is in the published version.
![graphdrag](https://user-images.githubusercontent.com/41024075/49755247-9cfd0180-fc75-11e8-9634-cde6ba2db9ac.PNG)

**Comment by jonathanolson** [comment]
I agree this looks nicer with a change to layering:

![area-model-layering](https://user-images.githubusercontent.com/480878/49762102-10a70a80-fc86-11e8-825b-4c8f496141ee.PNG)

@amanda-phet any objections to making the change to have it in front?

**Comment by jonathanolson** [comment]
Patched in master, and applied to the RCs. @amanda-phet can you verify that master (off phettest) looks good here?

**Comment by amanda-phet** [comment]
Looks good on all 4 sims!
