### ISSUE TITLE
Calculation String Max Width is too Short.

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/area-model-common#174]
For https://github.com/phetsims/QA/issues/230
The Calculation string on the partition screen of the Area Model Introduction sim has a large amount of room in could expand into when string test is long.
![longtestshort](https://user-images.githubusercontent.com/41024075/53607591-ab73fe80-3b7c-11e9-828d-ea765e3361ed.jpg)

**Comment by jonathanolson** [comment]
Should be fixed on master, thanks!
