### ISSUE TITLE
Internet explorer can't enter full screen

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/area-model-common#176]
**Device**
Bates
**OS**
Win 7
**Browser**
Internet Explorer
**Problem Description**
For https://github.com/phetsims/QA/issues/231 and https://github.com/phetsims/QA/issues/228
On these two sims, trying to enter full screen mode on Win 7 IE the browser throws an error and reloads the page without entering full screen.  I did a quick check on Area Model Multiplication and the published version doesn't seem to do this.  I didn't see an error in the console.
**Steps to reproduce**
1. Go to the sim and enter one of the screens
2. Open the phet menu and use full screen
3. Note error

**Comment by KatieWoe** [comment]
Error that pops up reads:
Internet Explorer has stopped working
A problem caused the program to stop working correctly. Windows will close the program and notify you if a solution is available.
I also saw this occur once while trying to open the console.

**Comment by KatieWoe** [comment]
Update.  It seems like it may be connected to or happen more often if you are inside a game level.

**Comment by KatieWoe** [comment]
Edit: I earlier said that I didn't see it in Win 10.  I dug a bit deeper and it does seem to happen there, though it doesn't show the error described in the above comment.

**Comment by jonathanolson** [comment]
Looks like a hard crash on the browser tab process. I don't see any notable way to resolve this. @ariel-phet let me know if this deserves more time to investigate.

**Comment by ariel-phet** [comment]
marking as `wontfix` - not a showstopping issue on IE

**Comment by ariel-phet** [comment]
Assigning to @KatieWoe to close once she is aware

**Comment by KatieWoe** [comment]
Happened on Generic screen in https://github.com/phetsims/QA/issues/319
