### ISSUE TITLE
Add title to game screens

### ISSUE THREAD

**Issue by amanda-phet** [phetsims/area-model-common#177]
To be consistent with other game screens, the level selection screens for all game screens (Area Model Multiplication and Area Model Algebra) should have the title "Choose Your Level!"

**Comment by jonathanolson** [comment]
Patched in master and on the 1.2 release branch. @amanda-phet how does that look?

**Comment by jonathanolson** [comment]
I'll have spacing better match ExEx.

**Comment by jonathanolson** [comment]
Spacing should match now (centered in the empty space). @ariel-phet does this look good to you? (I patched the branches)

**Comment by ariel-phet** [comment]
@jonathanolson the placement of "Choose Your Level!" looks good, but werent we going to make the tile buttons on the level selection screen spaced more like Ex Ex?

**Comment by jonathanolson** [comment]
Patched on master and the release branches, sorry about that! @ariel-phet does it look good now?

**Comment by ariel-phet** [comment]
@jonathanolson thanks, looks good. Closing
