### ISSUE TITLE
HTML downloads create more files than normal

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/area-model-common#179]
For https://github.com/phetsims/QA/issues/319, https://github.com/phetsims/QA/issues/318, https://github.com/phetsims/QA/issues/317, and https://github.com/phetsims/QA/issues/316.  When right clicking and using save-as on the sim it creates the html file and a new folder that contains something called "analytics.js.download"  Normally only the html file is created.  The published version did not create these extra folders either.  This was done on Win 10 chrome.

**Comment by KatieWoe** [comment]
![file](https://user-images.githubusercontent.com/41024075/57735130-d55b9e00-7660-11e9-8ec2-3f082425c481.png)
![files](https://user-images.githubusercontent.com/41024075/57735131-d55b9e00-7660-11e9-9127-0c2fbefb1b01.png)

**Comment by KatieWoe** [comment]
@amanda-phet pointed out that when you download there are two format options.  One does this and one behaves normally.  Not sure why the default is different here though, which may be worth looking at.  Also, I noticed some odd flickering as the sim started up.
![flashing](https://user-images.githubusercontent.com/41024075/57735595-5f583680-7662-11e9-85f1-b780c4ed5649.gif)

**Comment by jonathanolson** [comment]
Quick test on Mac chrome showed that the area-model 1.0 and 1.2 branches both create a downloadable folder with analytics.js. I'll check on Windows.

**Comment by ariel-phet** [comment]
@KatieWoe @jonathanolson I only think this is a problem if a build version on the website did not create a single file when using the download button

**Comment by jonathanolson** [comment]
I went back to the 1.0 release for area-model, built it locally, and did save-as (with the default, complete page), and it did include an analytics.js.download. So this doesn't look like a regression.

Additionally, saving just the "Web page only" version in Chrome (version 74, Windows 10) results in one file (no folder) that works. See:

![save-as](https://user-images.githubusercontent.com/480878/58583244-cd7b2c80-8210-11e9-8f9e-5dd8f5483f05.PNG)

So @ariel-phet correct me if I'm wrong, but I don't think this should block area-model 1.2.

**Comment by KatieWoe** [comment]
I agree with what @jonathanolson saw

**Comment by ariel-phet** [comment]
@jonathanolson agreed, should not block 1.2

@KatieWoe feel free to close unless you think anything more is necessary.
