### ISSUE TITLE
Old vibe sound button is still there

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/area-model-common#182]
**Test device:**
Dell
**Operating System:**
Win 10
**Browser:**
chrome
**Problem description:**
For https://github.com/phetsims/QA/issues/338 and https://github.com/phetsims/QA/issues/341
During this rc, sound in the game was switched from vibe to tambo.  This means that muting is controlled by the nav bar button.  However, the old yellow sound button is still present in the game screen.  It does not seem to do anything, and the nav bar button seems to work from what I've seen so far.
**Steps to reproduce:**
1. Go to a game screen
2. Play the levels with various combinations of muting.

**Screenshots:**
![bothsounds](https://user-images.githubusercontent.com/41024075/59114651-e1a3e580-8904-11e9-8deb-d31a0d68ba37.png)

Troubleshooting information (do not edit):

<details>

Name: ‪Area Model Algebra‬
URL: https://phet-dev.colorado.edu/html/area-model-algebra/1.2.0-rc.2/phet/area-model-algebra_all_phet.html
Version: 1.2.0-rc.2 2019-06-06 16:27:51 UTC
Features missing: touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.80 Safari/537.36
Language: en-US
Window: 1536x722
Pixel Ratio: 2.5/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 30 uniform: 4096
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {}

</details>

**Comment by KatieWoe** [comment]
Assigning @jbphet as well in case there is some trouble switching over.

**Comment by jbphet** [comment]
Good observation @KatieWoe.  This should go to @jonathanolson, since he did the conversion for this sim.

**Comment by jonathanolson** [comment]
Somehow I missed a commit in the cherry-picks. I'll make sure this is included in the next RC.

**Comment by KatieWoe** [comment]
Looks good in the rc's

**Comment by jonathanolson** [comment]
Thanks!
