### ISSUE TITLE
Slight touch area overlap in dimension boxes

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/area-model-common#183]
For https://github.com/phetsims/QA/issues/341, https://github.com/phetsims/QA/issues/340, https://github.com/phetsims/QA/issues/339, and https://github.com/phetsims/QA/issues/338
With the titles of accordion boxes again being clickable I noticed that the touch areas of closing the box overlaps a bit with the touch arrows to increase the dimensions of the area.  The area spinners take president and this is a very minor issue, if it is one at all.  I would be hesitant to decrease the size of these areas, so I suggest we keep this as is.
Red line drawn in shows approximate boundary of touch area for closing accordion box.
![slightestoverlap](https://user-images.githubusercontent.com/41024075/59126662-d95aa300-8922-11e9-80af-f94f353fd164.png)

**Comment by jonathanolson** [comment]
@ariel-phet and @amanda-phet, let me know if I should take down the vertical touch expansion slightly on the spinners so there is no overlap.

**Comment by amanda-phet** [comment]
I think we can leave them, but appreciate having it documented. Thanks @KatieWoe .
