### ISSUE TITLE
Internet Explorer Has No Sound

### ISSUE THREAD

**Issue by JRomero0613** [phetsims/area-model-common#184]
For https://github.com/phetsims/QA/issues/341 and https://github.com/phetsims/QA/issues/338 when testing on Windows 7 on Internet Explorer it was noticed that the game screens had no sound. There is not a sound button next to the PhET menu unlike all other devices and platforms tested. I'm not sure if this is an IE only issue or Windows 7 as well because this is the only IE I have tested, or if sound is even supported on IE. Other than this issue Windows 7 and IE seem to be functioning properly.

**Comment by KatieWoe** [comment]
Since the sound is now on tambo I believe sound would no longer be supported on IE.  Also, @JRomero0613 please remember to assign and label issues in the future.
