### ISSUE TITLE
Should erase button clear/hide keypad?

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/area-model-common#185]
For https://github.com/phetsims/QA/issues/341, https://github.com/phetsims/QA/issues/340, https://github.com/phetsims/QA/issues/339, and https://github.com/phetsims/QA/issues/338
Is in published sim
From Slack:
>Kathryn Woessner [1:01 PM]
>Related, should the eraser button get rid of the number before it's entered/numberpad?

>Jonathan Olson [1:12 PM]
>Sounds like a good question for Amanda. I could imagine the erase button clearing the keypad and hiding it

>Amanda McGarry [1:34 PM]
>the eraser is technically about clearing the model… so yeah I could see it clearing the keypad in this case. Since I wasn’t lead on this sim and didn’t do the interviews I can’t recall if there were any issues with this at that time. But I think that would be a good change to make. can you make an issue for it and assign to JO? You can mention that you talked it over with me in the issue.

![related](https://user-images.githubusercontent.com/41024075/59222478-d4962900-8b86-11e9-8eb9-186b4d5c24ee.gif)

**Comment by jonathanolson** [comment]
Patched in master. @KatieWoe can you confirm that this is the desired behavior now?

**Comment by jonathanolson** [comment]
Also patched branches.

**Comment by KatieWoe** [comment]
Looks good in master

**Comment by KatieWoe** [comment]
Looks good in the rc's

**Comment by jonathanolson** [comment]
Sounds good, closing!
