### ISSUE TITLE
Info boxes can disappear in full screen

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/area-model-common#188]
**Test device**
Dell
**Operating System**
Win 10
**Browser**
Firefox
**Problem description**
For https://github.com/phetsims/QA/issues/409, may happen in others. Was able to reproduce in published sim.
When the sim is in full screen clicking around the partial product box and other boxes in the area could cause all of the boxes to disappear.  This only seems to occur once, and you would need to reload to get it to happen again.  It can last anywhere from a split second to a fairly long time, needing several clicks to get everything back to normal.  Can be very unreliable. Mostly was able to reproduce on Generic and Variable screens

**Visuals**
![firefoxdisappear](https://user-images.githubusercontent.com/41024075/66675814-58d6e680-ec23-11e9-9a9c-9685330276a9.gif)

Troubleshooting information:

<details>

!!!!! DO NOT EDIT !!!!!
Name: ‪Area Model Algebra‬
URL: https://phet-dev.colorado.edu/html/area-model-algebra/1.2.0-rc.4/phet/area-model-algebra_all_phet.html
Version: 1.2.0-rc.4 2019-08-26 15:46:15 UTC
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:69.0) Gecko/20100101 Firefox/69.0
Language: en-US
Window: 1536x750
Pixel Ratio: 2.5/1
WebGL: WebGL 1.0
GLSL: WebGL GLSL ES 1.0
Vendor: Mozilla (Mozilla)
Vertex: attribs: 16 varying: 30 uniform: 4096
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 32767x32767
OES_texture_float: true
Dependencies JSON: {}

</details>

**Comment by jonathanolson** [comment]
I'm curious if something like `?rootRenderer=canvas` prevents this from occurring (i.e. whether it's specific to SVG).

**Comment by KatieWoe** [comment]
That query parameter did seem to work

**Comment by ariel-phet** [comment]
Considering this is rare and only happens once, and maybe fixed by Firefox in the future, I am marking deferred.

Next time we test this sim or make a change, we can see if the issue has been resolved in Firefox

**Comment by marlitas** [comment]
I'll check to see if this issue is resolved now.

**Comment by AgustinVallejo** [comment]
Played for some minutes trying to reproduce this bug on firefox, and I'm no longer seeing it neither in the published nor current version. I think this is good to close.
