### ISSUE TITLE
Crash when entering Full screen in IE

### ISSUE THREAD

**Issue by loganbraywork** [phetsims/area-model-common#189]
**Test device**
Windows 7 Personal Laptop

**Operating System**
6.1

**Browser**
IE 11.0.9600.19504

**NOTES**
Issue similar to https://github.com/phetsims/wave-interference/issues/451.

Seems a similar issue on this sim has been closed before about 6 months earlier, but still making an issue for posterity. See https://github.com/phetsims/area-model-common/issues/176

Does not occur in the published version.

**Problem description**
From https://github.com/phetsims/QA/issues/409

Sim crashes when full screen is entered on generic screen or variables screen. 

**Steps to reproduce**
1. Enter either the Variables screen or Generic screen
2. Enter full screen using the Phet menu

**Visuals**
![2019-10-11IECrashAreaMdlAlg](https://user-images.githubusercontent.com/54685448/66681156-52e70280-ec2f-11e9-9582-ef6c16025aad.gif)

Troubleshooting information:
!!!!! DO NOT EDIT !!!!!
  
Name: ‪Area Model Algebra‬

URL: https://phet-dev.colorado.edu/html/area-model-algebra/1.2.0-rc.4/phet/area-model-algebra_all_phet.html

Version: 1.2.0-rc.4 2019-08-26 15:46:15 UTC

Features missing: touch, fullscreen

Flags: pointerEnabled, msPointerEnabled

User Agent: Mozilla/5.0 (Windows NT 6.1; WOW64; Trident/7.0; SLCC2; .NET CLR 2.0.50727; .NET CLR 3.5.30729; .NET CLR 3.0.30729; Media Center PC 6.0; .NET4.0C; .NET4.0E; rv:11.0) like Gecko

Language: en-US

Window: 1366x650

Pixel Ratio: 1/1

WebGL: WebGL 0.94

GLSL: WebGL GLSL ES 0.94

Vendor: Microsoft (Internet Explorer)

Vertex: attribs: 16 varying: 15 uniform: 512

Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)

Max viewport: 16384x16384

OES_texture_float: true

Dependencies JSON: {}

**Comment by jonathanolson** [comment]
@ariel-phet, what time should I spent investigating this? It seems likely that there's little we could do, and it seems hard to track down what would trigger this.

**Comment by ariel-phet** [comment]
I think we can close this one as `wontfix`
