### ISSUE TITLE
AreaScreenView config.decimalPlaces should be optional

### ISSUE THREAD

**Issue by Denz1994** [phetsims/area-model-common#190]
As noted in https://github.com/phetsims/phet-info/issues/115#issuecomment-549892311, the use of config.decimalPlaces is not truly a required field. I made a change to `ProportionalAreaScreenView.js` that asserts `decimalPlaces` is supplied by the client. This may go against the original intention of its implementation and thus the responsible dev should review.

Assigning to @jonathanolson.

**Comment by jonathanolson** [comment]
Looks good to me, thanks!
