### ISSUE TITLE
Use phet-core.OrientationPair 

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/area-model-common#192]
Discovered while investigating https://github.com/phetsims/geometric-optics/issues/42.

phet-core.OrientationPair and area-model-common.OrientationPair provide identical functionality. No surprise there, since @jonathanolson wrote both of them.  Replace the latter with the form.

**Comment by AgustinVallejo** [comment]
Tried changing all the file imports to `phet-core`, but apparently the functionality is not exactly the same, and it is raising multiple errors. It seems this will require a bigger effort, or pairing with a more experienced dev.

Just an example, in Area.js:67, originally `this.totalProperties.values` is listed as an Array, whereas with the phet-core.OrientationPair, it is a `() => unknown[]`, which is not supported by DerivedProperty. Similar errors appear all over the place.

@marlitas @pixelzoom let me know what should be done here.

**Comment by pixelzoom** [comment]
As I pointed out in https://github.com/phetsims/area-model-common/issues/192#issue-997252220...   @jonathanolson wrote both phet-core.OrientationPair and area-model-common.OrientationPair.  I recommend pairing with him to understand why there are differences, whether the implementations can be combined, etc.

**Comment by pixelzoom** [comment]
I also want to point out that when I created this issue, the 2 implementations of OrientationPair were much more similar. Since then, phet-core.OrientationPair has been converted to TypeScript and diverged.  This seems like an additional argument for unifying the implementations.

**Comment by AgustinVallejo** [comment]
Completed this with @jonathanolson and deleted `area-model-common.OrientationPair`. Now using phet-core's one.
