### ISSUE TITLE
Decide whether to turn off UI sounds on next publication

### ISSUE THREAD

**Issue by markgammon** [phetsims/area-model-common#193]
As part of the work done for https://github.com/phetsims/vegas/issues/77, UI sounds got turned on for this simulation.  Before the sim is published again from master, we should decide whether to turn the UI sounds off, leave them on and design and implement sounds for the rest of the interactions, or publish with a partial sound design.

If the decision is to turn them off, this can be accomplished by adding the following line to the end of the sim's `-main.js` file:

```js
  soundManager.setOutputLevelForCategory( 'user-interface', 0 );
```

**Comment by AgustinVallejo** [comment]
In the above commit I turned off UI sounds for the sims area-model + algebra, decimals, introduction, multiplication. I saw there's also area-builder but I assumed it shouldn't be included in the scope of this issue.

Please confirm this, and close if done @marlitas

**Comment by marlitas** [comment]
That seems correct. I checked and I do not see area-builder importing area-model-common. Looks good to close.

**Comment by amanda-phet** [comment]
Does this impact https://github.com/phetsims/area-model-algebra/issues/8 and https://github.com/phetsims/area-model-multiplication/issues/9 ? 

We decided to keep the UI sounds on, and use a grab/drop sound for the non-common components.

**Comment by AgustinVallejo** [comment]
Will discuss with @marlitas and @Luisav1. I can take on those issues
