### ISSUE TITLE
Replace sim-specific code with LevelSelectionButtonGroup

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/area-model-common#194]
Related to https://github.com/phetsims/vegas/issues/108 ...

LevelSelectionButtonGroup is a new vegas UI component for creating the level-selection buttons for games.  It replaces boilerplate code in sims, and provides a consistent PhET-iO tandem structure.  Please convert this sim to use LevelSelectionButtonGroup.

**Comment by marlitas** [comment]
This will be completed as part of the region and culture publication.

**Comment by Luisav1** [comment]
This should be fixed in the commit above. @pixelzoom could you review the changes? Thanks!

**Comment by pixelzoom** [comment]
Looks good to me - closing.
