### ISSUE TITLE
Add gameLevels query parameter

### ISSUE THREAD

**Issue by Luisav1** [phetsims/area-model-common#198]
While meeting, we realized AM sims don't have a `gameLevels` query parameter, similar to https://github.com/phetsims/graphing-lines/issues/144.

**Comment by pixelzoom** [comment]
In the above commits, I added the `gameLevels` query parameter for area-model-algebra and area-model-multiplication.

Unfortunately, there is also some layout work to be done.  The layout is apparently expecting 6 levels, and it looks very ugly with anything else.  

For example, area-model-algebra with `gameLevels=1,3,5,6` looks like this:

<img width="1010" alt="screenshot_3010" src="https://github.com/phetsims/area-model-common/assets/3046552/e4684154-becf-4490-8ee2-53e1c149cb04">

And with `gameLevels=1,3,5,6` it looks like this, not vertically centered:

<img width="1009" alt="screenshot_3012" src="https://github.com/phetsims/area-model-common/assets/3046552/9b41b4d1-ec18-467d-bde8-23c0658e9e88">

**Comment by pixelzoom** [comment]
https://github.com/phetsims/area-model-common/commit/4c2108a91cf2e73d69a5832bc604cb96467959d6 addresses the layout of the buttons in rows.   

https://github.com/phetsims/vegas/commit/02b9e482d99cbcd37156dbbdc203bacdc1c16e48 keeps the buttons centered on the screen when using `?gameLevels`.

Ready for review by @amanda-phet.   Please review both area-model-algebra and area-model-multiplication.
