### ISSUE TITLE
Handling for collapsed accordion boxes

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/area-model-common#2]
Design docs show the panels fitted up to a collapsed box:
![screen shot 2017-05-10 at 10 17 35 am](https://cloud.githubusercontent.com/assets/480878/25909350/23f0ad56-356a-11e7-9bf5-06e06141788b.png)
and shifted down when the box is opened:
![screen shot 2017-05-10 at 10 19 32 am](https://cloud.githubusercontent.com/assets/480878/25909367/3564d8be-356a-11e7-923e-cb0e5cb57466.png)

Other simulations don't shift panels up/down based on whether the accordion boxes are collapsed or not, and I don't see a mockup for the "Problem" box being collapsed.

Should things stay in place when a box is collapsed? And if so, could we move the "Total area of model" box under the other two panels so that there is not an initial gap (e.g. atomic-interactions)?

**Comment by samreid** [comment]
In some UI toolkits it is important for the layout to reflow when components resize, but in this sim it seems to me that those accordion boxes aren't taking up much space and it would be awkward for other controls to jump around when toggling the accordion.

**Comment by ariel-phet** [comment]
Seems like a good question for design meeting

**Comment by amyh-phet** [comment]
We can discuss at design meeting on 05/11.

**Comment by amyh-phet** [comment]
Discussed at design meeting on 05/11/17.  Decision made to have all panels remain in place when collapsible panels are closed.  This behavior is currently implemented in sim.

**Comment by jonathanolson** [comment]
Closing, thanks!
