### ISSUE TITLE
Clicking on edit readouts

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/area-model-common#23]
Can the edit readouts (next to the edit buttons) also be clicked to open the keypad? This would be very helpful for touch devices (if the touch area can cover the area), but may also be useful for mouse use.

**Comment by amyh-phet** [comment]
I think yes, users can click either the edit button or edit readouts to open the keypad.  I agree that the touch area should include both items.

**Comment by jonathanolson** [comment]
Implemented, can you try it out?

**Comment by amyh-phet** [comment]
Looks good.  Nice to be able to click box or edit button.
