### ISSUE TITLE
Coloring on Gridlines on Raccoon and Decimals screen

### ISSUE THREAD

**Issue by amyh-phet** [phetsims/area-model-common#27]
Currently, the grids on the Raccoon and Decimals screens contain darker lines.  For example, on the 20x20 scene on the Raccoon screen, the gridlines for 10 are darker.  

After discussing the sim today, the gridlines should all be the same color to avoid users mistaking these lines as partition lines.

**Comment by jonathanolson** [comment]
Done in master.
