### ISSUE TITLE
Don't show dock (or inactive partition lines) when size is below snapping

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/area-model-common#28]
For example on the 100x100 screen (where partition lines snap to multiples of 10), if the total height is 7, I'd like for it to act the same way it would if the height was 1 (dock/partition line disappears, unless it is actively being dragged).

Does that sound ok?

**Comment by amyh-phet** [comment]
Sounds reasonable to me.

**Comment by jonathanolson** [comment]
Done.
