### ISSUE TITLE
Drag behavior of the rectangle drag handle

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/area-model-common#3]
I'm anticipating a slightly unappealing "stutter" while dragging if this drag handle is always a fixed distance from the rectangle. The mouse (in a drag) would not stay matched with the drag handle due to snapping.

I'd like to consider having the drag handle be able to slightly extend/retract from the rectangle while dragging (but only diagonally), so that it feels more natural.

May become obvious if this is needed once I start with the naive implementation with no extension/retraction.

**Comment by amyh-phet** [comment]
I think having the drag handle be able to slightly extend/retract from the rectangle while dragging seems like a reasonable way to make the interaction feel more natural and avoid a "stutter" behavior.

**Comment by jonathanolson** [comment]
Implemented on master. Let me know if you want a dev version for testing, or if you can use phettest.colorado.edu.

**Comment by amyh-phet** [comment]
PhET test should work.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by amyh-phet** [comment]
I think the drag behavior seems reasonable.  A bit of a stutter on the 20x20 screen, but nothing that makes it hard to use.

**Comment by jonathanolson** [comment]
Sounds good, closing.
