### ISSUE TITLE
Model selection combo box for screens 2 and 3

### ISSUE THREAD

**Issue by amyh-phet** [phetsims/area-model-common#30]
@amanda-phet   and @kathy-phet 
Can you give feedback on these mockups of the combo box ideas from our meeting today?

Default
![s2_combo_box](https://cloud.githubusercontent.com/assets/13650180/26332349/6484773c-3f13-11e7-83ee-d6b62f1a654c.png)

Combo box open
![s2_combo_box_open](https://cloud.githubusercontent.com/assets/13650180/26332348/6483463c-3f13-11e7-8bdf-7ad0abee86fc.png)

Carousel
![s2_carousel](https://cloud.githubusercontent.com/assets/13650180/26332370/79572466-3f13-11e7-8e42-4944199a83c2.png)

One issue we will need to remember is spacing for calculation panel and height label on screen 3
![s2_sim](https://cloud.githubusercontent.com/assets/13650180/26332391/8e5212b8-3f13-11e7-91af-f782c303ca07.png)
![s3_sim](https://cloud.githubusercontent.com/assets/13650180/26332392/8e547148-3f13-11e7-82ca-390c9dd8e865.png)

**Comment by kathy-phet** [comment]
Amy,

With the combo box grid, I would lay it out slightly differently, with the diagonal being 1x1 then 2x2 then 3x3. The across the top I would put the 2 vertical divides the 3 vertical divides. Down the left column I would put two horizontal divides then 3 horizontal divides. And the fill the remaining two spots following that pattern. The farther right the more vertical divides the farther down the more horizontal divides.

Kathy

Sent from my iPhone

On May 22, 2017, at 5:25 PM, amyh-phet <notifications@github.com<mailto:notifications@github.com>> wrote:


Assigned #30<https://github.com/phetsims/area-model-common/issues/30> to @kathy-phet<https://github.com/kathy-phet>.

**Comment by amyh-phet** [comment]
Sounds good.  Away from my computer for a few hours, but I'll update the mock-up tonight.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by kathy-phet** [comment]
Regarding the carousel or the combo box, I am split. I like that once you select your model with the combo box, you get to focus solely on building that model with the combo box hiding the other models. And I like that you can see all the models at once.

With the carousel I like that you see that it is an option to select different models at all. And it's not as hidden a functionality.

I agree maybe moving the model select to the top above problem might make sense for the combo box approach.

Kathy



Sent from my iPhone

On May 22, 2017, at 5:25 PM, amyh-phet <notifications@github.com<mailto:notifications@github.com>> wrote:


Assigned #30<https://github.com/phetsims/area-model-common/issues/30> to @kathy-phet<https://github.com/kathy-phet>.

**Comment by amyh-phet** [comment]
Summarizing changes we would like to make:

- Remove docks/partition handles from model.

- Default for screen would show model with 2 partition lines (one height, one for length).  Model would be partitioned into four smaller areas.

- Edit boxes/buttons for four partitioned heights/lengths would be visible on default.

- Dimension lines (purple/green lines) are visible along height and width of model, but no value for either dimension line is shown.

**Comment by amyh-phet** [comment]
@jonathanolson  I'm assuming a combo box would work best given space constraints, but just curious if you have ideas on how to make the carousel fit if we wanted to go that route?

**Comment by amanda-phet** [comment]
I like the combo box at the top as well, but it breaks with the location of the scene selection buttons on the first screen. However since it's a different UI component I think it will be fine to have it in a new location.

**Comment by amyh-phet** [comment]
@amanda-phet @kathy-phet  @ariel-phet   I know we discussed using buttons in the combo box to select the grid size on the generic model screens (Screens 2 and 3).  After mocking up the list of labels for the combo box, I'm wondering if the buttons are necessary.  Can you give feedback on the two options below?

Button option:
![combo_box_open](https://cloud.githubusercontent.com/assets/13650180/26502846/a2304508-41fb-11e7-9656-daf9afd6481e.png)

List option:
![combo_box_list_open](https://cloud.githubusercontent.com/assets/13650180/26502860/b0e253b6-41fb-11e7-857d-0e6ff7cee03d.png)

**Comment by jonathanolson** [comment]
Initial version of this implemented in master.

Using the normal drop-down style for now, as it was much easier to implement quickly. The common code will need some changes long-term anyways, so it won't be a huge problem to change the appearance to the more button-like one if desired.

Should digit counts (on the 2nd screen) be limited slightly differently? For a 2x2, do you want 3-digit and 2-digit editable fields, or 2-digit and 1-digit editable fields?

How should the keypad work? Currently I'm doing the 'lazy' thing to have it independent for each size, but the keypad could be closed any time a new size is switched to.

How should the erase button work? Currently it only clears the particular 'size'.

**Comment by kathy-phet** [comment]
I like the button option better myself, as it seems a bit easier to parse.  But would be ok with the list if you prefer that.

Sent from my iPhone

On May 26, 2017, at 10:11 AM, amyh-phet <notifications@github.com<mailto:notifications@github.com>> wrote:


@amanda-phet<https://github.com/amanda-phet> @kathy-phet<https://github.com/kathy-phet> @ariel-phet<https://github.com/ariel-phet> I know we discussed using buttons in the combo box to select the grid size on the generic model screens (Screens 2 and 3). After mocking up the list of labels for the combo box, I'm wondering if the buttons are necessary. Can you give feedback on the two options below?

Button option:
[combo_box_open]<https://cloud.githubusercontent.com/assets/13650180/26502846/a2304508-41fb-11e7-9656-daf9afd6481e.png>

List option:
[combo_box_list_open]<https://cloud.githubusercontent.com/assets/13650180/26502860/b0e253b6-41fb-11e7-857d-0e6ff7cee03d.png>

**Comment by jonathanolson** [comment]
I personally prefer the button look.

**Comment by amyh-phet** [comment]
I also like the button look and I think it will work better with younger users.

**Limiting digits on 2nd screen:** 
I think it makes sense to do this differently from screen 3.  Here's how I think it would work best to limit keypad entry:  
1 edit box visible - 3 digits
2 edit boxes visible - 3 digits, 2 digits
3 edit boxes visible -  3 digits, 2 digits, 1 digit

This means a 2x2 would have 3 digit and 2 digit editable fields.  

**Keypad** 
I'm not sure the options we have on how the keypad should function.  Current implementation is behaving as I expected.

**Erase button**
I think is should only clear the grid that is visible on the play space as it does now.

**Comment by jonathanolson** [comment]
The way you described limiting digits is what I already implemented.

> I'm not sure the options we have on how the keypad should function. Current implementation is behaving as I expected.

Is it weird if you open the keypad on 2x2, switch to 1x1 (which makes the keypad disappear), but then switch back to 2x2 and it re-opens? I'm fine keeping as-is, but that felt slightly weird to me.

> Erase button
> I think is should only clear the grid that is visible on the play space as it does now.

Sounds good.

**Comment by amyh-phet** [comment]
I agree the keypad appearing/disappearing does seem weird.  Might be a good thing to discuss in design meeting this week.

**Comment by jonathanolson** [comment]
Multiple other developers cautioned against the different style ComboBox.

I'd like to create a version of it as a separate component on a branch for testing, but I'd recommend that a broader design effort should be made to think about components like this, and when we'd want to use it.

**Comment by jonathanolson** [comment]
Implemented the grid option. The list option is still available with the query parameter `?combobox`.

**Comment by amyh-phet** [comment]
I'll see how this goes in interviews on 6/14 and 6/15 and go from there.

**Comment by amyh-phet** [comment]
No issues observed in interviews.  Closing.
