### ISSUE TITLE
Make Total Area, Area Model Calculation, and Partial Products panels visible on default

### ISSUE THREAD

**Issue by amyh-phet** [phetsims/area-model-common#31]
With current implementation, the panels can easily appear/disappear as user interacts with model.   

Changes to current behavior:

- Panels always visible.

- If user has not entered any values for length/height on model, then a ? will be used to show any readouts in the Total area panel, any partial products displayed on the model (product or factor), and in the calculation panel below the model.

If a user has entered a value for height OR length, then:
Total area or Partial Product - Product selection (A button) = ?
Calculation panel (for both options) and Partial Product factors (a x b button) will display a color-coded box for any undefined dimension and the number entered for any defined dimension.

![s2_no_entry_pp_p_line_by_line](https://cloud.githubusercontent.com/assets/13650180/26499965/878e5050-41f1-11e7-9735-3404f0667a6d.png)
![s2_no_entry_pp_f_all_questions](https://cloud.githubusercontent.com/assets/13650180/26499972/8ff90a0a-41f1-11e7-9095-88a0de91e8e7.png)
![s2_1_entry_pp_p_line_by_line](https://cloud.githubusercontent.com/assets/13650180/26499983/a212a9c6-41f1-11e7-899f-dc24af0d3ec4.png)
![s2_1_entry_pp_f_all_lines](https://cloud.githubusercontent.com/assets/13650180/26499989/a64c4e84-41f1-11e7-9bd7-90d5d02a52bd.png)

**Comment by jonathanolson** [comment]
This mockup (and the discussion from the last design meeting) has the coloring of partial products described by https://github.com/phetsims/area-model-common/issues/7 that was decided against before. I'd just like to double-check that partial products should be color-coded?

**Comment by amyh-phet** [comment]
My apologies.  Copy and pasted in the mockup and didn't fix colors.  Let's try again. Factors displayed on model should not be color coded.  Color coding in calculation panel is okay.
![s2_1_entry_pp_f_all_lines](https://cloud.githubusercontent.com/assets/13650180/26596138/f1b7376c-452a-11e7-9bc0-f579a867344e.png)

**Comment by jonathanolson** [comment]
Changes to this are done, the drop-down (https://github.com/phetsims/area-model-common/issues/30) shouldn't change how this works.

Does it look as expected?

**Comment by amyh-phet** [comment]
@jonathanolson    Partial products displays are behaving as expected, but there seems to be an issue with the calculation panel opening below the model.   The panel doesn't open until a value for both height and width are entered.  This happens regardless of the setting in the Partial products panel.

One length entered - no calculation panel visible.
![calc_panel_issue_pp_a_alllines](https://cloud.githubusercontent.com/assets/13650180/26602784/d9e82bb6-4541-11e7-95d1-9b8ce7ceb56a.png)
![calculation-panel_visibility_issue-pp_f_linebyline](https://cloud.githubusercontent.com/assets/13650180/26602815/ed570d66-4541-11e7-8617-626d260852b2.png)


Length and height entered, panel becomes visible.
![calculation_panel_issue](https://cloud.githubusercontent.com/assets/13650180/26602827/f7b4ec92-4541-11e7-916e-df53337f50bf.png)

**Comment by jonathanolson** [comment]
I'm having trouble reproducing that, can you give the exact instructions (and ensure area-model-common and area-model-multiplication are fully pulled?):
![prop-open](https://cloud.githubusercontent.com/assets/480878/26604263/fe81192e-4546-11e7-8d29-c89d64ad1af2.PNG)

**Comment by amyh-phet** [comment]
I'll pull again and see what if I can duplicate the issue.

**Comment by amyh-phet** [comment]
@jonathanolson   After pulling all repos again, I cannot reproduce the issue for either screen.

**Comment by amyh-phet** [comment]
Issue is addressed.
