### ISSUE TITLE
Change 4x4 scene on Decimals screen to 3x3 grid

### ISSUE THREAD

**Issue by amyh-phet** [phetsims/area-model-common#32]
Deltas:

- Grid shows 0.1 units for a 3x3 square.

- Drag handles to create rectangle and place partition lines snap to 0.1 units.

- Spinners change number by 0.1.

- Scene selection button reads 3x3
![decimals_3x3_default](https://cloud.githubusercontent.com/assets/13650180/26503420/da1c4bcc-41fd-11e7-88e9-32eb9ee124b0.png)

**Comment by jonathanolson** [comment]
Implemented, but this will create new layout issues we'll need to handle that can't be fixed by rotating the text:

![3x3](https://cloud.githubusercontent.com/assets/480878/26595548/0307e95a-4529-11e7-84a8-9413a107d518.png)

@amyh-phet, thoughts?

**Comment by amyh-phet** [comment]
@jonathanolson   I'll look into this later today and see what I can come up with.

**Comment by amyh-phet** [comment]
Completed. Closing.
