### ISSUE TITLE
Keep multiplication display consistent on Screen 2 and 3

### ISSUE THREAD

**Issue by amyh-phet** [phetsims/area-model-common#33]
On Screen 2,  when Factors are displayed, they should be shown with an x for multiplication.
![17_s2_12x10_factor_all_lines](https://cloud.githubusercontent.com/assets/13650180/26585570/bb2291f4-4509-11e7-9b3e-56b8cdc5f69e.png)

On Screen 3, the button to select Factors in the Partial Products panel should show parenthesis instead of an x to indicate multiplication.
![factor_button_s3](https://cloud.githubusercontent.com/assets/13650180/26585714/32abf044-450a-11e7-85d9-7b6a9adb4ef9.png)

**Comment by jonathanolson** [comment]
Should be done in master.

**Comment by amyh-phet** [comment]
@jonathanolson   This looks good.  Closing
