### ISSUE TITLE
Panel layout switching between 2nd and 3rd screen

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/area-model-common#36]
Currently if you switch between these two screens, it's possible to see that there's a slight "shift" because the "Product" and "total area" parts allow a bit more vertical room for exponents.

Is it fine if the 2nd screen also allows this much room, so there is no shift in panels when switching between the two screens?

**Comment by amyh-phet** [comment]
I'm fine with adding more room to the panels in the 2nd screen to avoid panels shifting when switching between screens.
