### ISSUE TITLE
Game questions

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/area-model-common#37]
Now that I've got some of the game mechanics testable, it would be valuable to see how it may differ from the exact design doc:

- There are some dynamic/autofill entries that seem to be fully specified (so will just be filled in 100% of the time). Exists on levels 3-6, 4-2, 4-5 and 4-6 (numbers).
- Some levels are transposes of others, so since this is done automatically I've only included them as one. Exists with (4-5 4-6) (5-1 5-2) (5-3 5-4) numbers, and (4-2 4-3) variables.
- The "dimension line labels are dynamic/autofill if all partition sizes on that side are editable, otherwise it's given" rule looks to be potentially broken by descriptions of 6-1 (numbers) and 6-1 (variables). Additionally, 3-1 and 5-1 (variables) seem to be identical to each other with this rule. Does that need to be updated?
- Other sims use "Show Answer" for game questions. Can we use that, or is "Show Solution" preferred?
- It appears that the game never uses dynamic/autofill partition sizes. Would that open up more space for questions?

I'll be available on Skype if it's easier to discuss there.

**Comment by amyh-phet** [comment]
@jonathanolson  I can chat via Skype after 4 pm today.  Will that work for you?

**Comment by jonathanolson** [comment]
Works great!

**Comment by jonathanolson** [comment]
All actionable items here implemented (added horizontal/vertical dimension line labels as 'horizontalTotal' and 'verticalTotal' in the challenge specifications file).

Feel free to close if you don't need this issue (or leave open if you want notes about the first two bullet points above).
