### ISSUE TITLE
Readout-like border when editing a polynomial?

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/area-model-common#38]
It may be a good cue to put a border around the readout while editing a polynomial, like the readouts while editing a term.

Current appearance:
![screen shot 2017-06-06 at 2 02 22 pm](https://user-images.githubusercontent.com/480878/26849315-e8244d70-4ac0-11e7-9bf2-137b0db005ca.png)

**Comment by amyh-phet** [comment]
@jonathanolson   I agree that it would be good to have a border around the readout.  Let me know if you need a mockup to implement.

**Comment by jonathanolson** [comment]
Implemented removal of readout.
