### ISSUE TITLE
Add valueColor to NumberPicker

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/area-model-common#4]
@pixelzoom, any objections to me adding `valueColor` as an option to NumberPicker that controls the color of the displayed value?

**Comment by pixelzoom** [comment]
Sounds great.

**Comment by jonathanolson** [comment]
Just want to confirm with @amyh-phet that the colored text in the number pickers (spinners) is desired. It looks harder to read when being pressed (I prefer the black text), and the last design meeting discussed how we didn't want too much colored:
![screen shot 2017-05-13 at 11 37 44 pm](https://cloud.githubusercontent.com/assets/480878/26031566/624aaaca-3835-11e7-96a0-c7cb657cb03b.png)
![screen shot 2017-05-13 at 11 38 03 pm](https://cloud.githubusercontent.com/assets/480878/26031568/6ad2fb98-3835-11e7-817b-09d91d5174b5.png)

**Comment by pixelzoom** [comment]
Blue on blue certainly looks harder to read to me.

**Comment by amyh-phet** [comment]
Let's implement with the black number.  I agree that it is easier to read.  I'll look in interviews to make sure students map the height/width on the model to the spinners in the problem panel.

**Comment by jonathanolson** [comment]
Already as desired in implementation, closing.
