### ISSUE TITLE
[Game] Should variables game keypad adjust available buttons?

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/area-model-common#40]
For instance, if it's entering a constant, the x^2 and x buttons should not be used for a correct answer. Should these be visible, or is it too much of a "hint" if they are not there?

**Comment by amyh-phet** [comment]
@jonathanolson    Decision made to keep all buttons active on keypad even if user doesn't need option for a correct answer.   Felt like removing x^2 and x was too much of a cue to correct answer.  Closing.
