### ISSUE TITLE
[Game] Dynamic dimension line label visibility

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/area-model-common#41]
For doing things like Variables 6-1, we want to hide the dimension line label until ALL editable partition sizes on that side are filled in (it seems).

Does this generalize to the others, like numbers 4-1 where there are three editable partition sizes on one side? (What should the numbers 4-1 dimension line label show if 1 value is filled in and 2 are not?)

**Comment by amyh-phet** [comment]
@jonathanolson 

We will need to make some changes to the logic for displaying dimension lines.

- Numbers 3-1, 4-1, 4-4 and Variables 3-2.  For these questions, the dimension line labels should be visible.  The value should also be visible in the Product panel.

- Numbers 5-1 and 5-3 - Dimension line labels should NOT be visible.  The value should also be hidden in the Product panel.

**Comment by jonathanolson** [comment]
I believe this is implemented. Can you verify the behavior for Numbers level 5? (Dimension line labels never shown for those challenges).

**Comment by amyh-phet** [comment]
@jonathanolson    My apologies as I was unclear in my earlier post.  The labels along the dimension lines and in the Product panel should be visible once a user enters a value using the keypad. 

The values should disappear if the user has entered an incorrect value and presses the Check button.

**Comment by jonathanolson** [comment]
I'd like some further clarifications:

> The labels along the dimension lines and in the Product panel should be visible once a user enters a value using the keypad.

Is this describing the changes only for 5-1 and 5-3, or also the other challenges mentioned above?

Currently "dynamic" means "show a computed value only if all of the inputs are filled in and not marked incorrect". This is visible on numbers 6-1.

Then my previous understanding of 5-1 and 5-3 from the above comments was that "hidden" was the desired setting (never shown). Then I understood "hidden, but show the value with 'show answers'".

My current understanding, given that 5-1 and 5-3 only have one editable on each side, is that "dynamic" is exactly what you are describing, and there is no need for a complicated "hidden" type of field. Dynamic, in this case, would mean:

- It's initially hidden
- When the user fills in the partition size, the dimension line label gets filled in with the computed value (based on what the user puts in)
- If check is pressed and the partition size is incorrect, the dimension line label disappears.
- The next edit to the partition size again fills in the dimension line label (again, computed).

This is consistent with the dynamic changes requested in https://github.com/phetsims/area-model-common/issues/55.

I'm planning on changing it back to dynamic, but I'll leave in the code to handle "hidden" variants in case they are needed. (If "hidden" state is not needed, leave this open so I can make sure to remove it).

**Comment by jonathanolson** [comment]
A note: dynamic dimension line values are not currently properly filling in with "show solutions", checking.

**Comment by jonathanolson** [comment]
Implemented changes described. Can you try 5-1 and 5-3 (numbers) to make sure they behave as expected?

**Comment by amyh-phet** [comment]
Appears to be behaving as expected for 5-1 and 5-3.   Closing for now.
