### ISSUE TITLE
[Game] Show answers for variables 6-1

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/area-model-common#42]
If the user gets one of the values correct and one wrong, should we detect that and only change the "wrong" value? Otherwise occasionally something like (9, 4) would switch to (-4, 9) where it transposes the 9 that they have.

**Comment by amyh-phet** [comment]
I think it makes sense to only flag the "wrong" value and change that.  I wouldn't want to transpose the 9 as you mentioned in your example.

**Comment by jonathanolson** [comment]
Implemented.

**Comment by amyh-phet** [comment]
@jonathanolson   This looks close to what I was imagining.  I still get a correct number flagged as incorrect when I don't think it should be flagged. 

Here's the initial challenge:
![6-1-initial](https://user-images.githubusercontent.com/13650180/27102998-76dc2da2-5044-11e7-81a4-6c8fca59780d.png)

After the first incorrect attempt, both answers are flagged as incorrect even though one answer is correct:
![6-1_1st_incorrect](https://user-images.githubusercontent.com/13650180/27103027-8a197e88-5044-11e7-9fef-ce705e47db8b.png)

After a second incorrect attempt;
![6-1_2nd-incorrect-attempt](https://user-images.githubusercontent.com/13650180/27103054-9ecdffac-5044-11e7-9bfb-d88e2cbdeaef.png)

To avoid confusion, the horizontal entry should have been marked as correct on the first attempt and only the vertical editable box would be marked incorrect.

**Comment by jonathanolson** [comment]
I believe the decision (I didn't write it down) from https://github.com/phetsims/area-model-common/issues/39 was to show both as incorrect in that situation. Showing one correct feels fairly arbitrary.

Should it instead randomly choose which one is shown as correct, and which as incorrect? (If the user then sets the one marked as "correct" to the other value, we'd have the same problem with having a "correct" answer with an "incorrect" highlight.

For example, say the correct answers are 2 and 4, thus:

- (2,4) and (4,2) are both correct answers
- (2,2) and (4,4) are the cases we're worried about.

Current method: We flag (2,2) so both are incorrect. If the user changes one box to 4 (correct) and hits "check", they get a smiley face even though one box still had the "incorrect" highlight.

Proposed method: So say we flag (2,2) such that it's (2-correct,2-incorrect), highlighting one box as incorrect. Then if the user changes the box marked as correct to 4, giving them the state (4-correct,2-incorrect), again they would get a smiley face even though a box had the "incorrect" highlight.

My proposed solution (the best I can think of so far) would be to remove the "incorrect" highlight on both when one is edited in this situation. E.g. it flags as (2-incorrect,2-incorrect), but when they edit the first to 4 it would be (4-correct,2-correct).

Thoughts?

**Comment by amyh-phet** [comment]
I like your proposed solution of removing the "incorrect" highlight on both when one is edited in the situation described.

**Comment by jonathanolson** [comment]
Implemented desired highlight, let me know how it looks.

**Comment by amyh-phet** [comment]
I like the highlight as it is now functioning.  One last issue.  When I show answer, the dimension line labels and Product panels are not showing the correct answer.
![screen shot 2017-06-14 at 8 56 29 am](https://user-images.githubusercontent.com/13650180/27139205-9a3a4a68-50df-11e7-974e-ef16f0504ad1.png)

**Comment by jonathanolson** [comment]
Implemented the proper showing of answers (will also switch top/bottom to match the shown partition sizes)

**Comment by amyh-phet** [comment]
Looks good.  I'll review with the team and then close the issue if all looks well.

**Comment by amyh-phet** [comment]
@jonathanolson   I feel like something isn't working properly on these challenges again.  Tried reviewing with @amanda-phet and here's what happened.

Challenge appears:
![6_1_start](https://user-images.githubusercontent.com/13650180/27302379-1c19fa2a-54f4-11e7-8886-05db9df31aa6.png)

Entered first answer using one of the correct factors for both answers:
![6_1_entered_8_8](https://user-images.githubusercontent.com/13650180/27302390-27d14120-54f4-11e7-9dfb-876d87cb4ce0.png)

Used Check button; both answers flagged as incorrect:
![6_1_1st_incorrect](https://user-images.githubusercontent.com/13650180/27302401-35cb5036-54f4-11e7-8f1d-b61dc01567f1.png)

Fixed one answer, but second answer is still flagged incorrect (even thought it is correct); check button is inactive:
![6_1_fixed_one](https://user-images.githubusercontent.com/13650180/27302429-4f55c2b6-54f4-11e7-9010-6407c7f79a75.png)

Entered two correct answers (basically went back and entered the same answer to remove incorrect highlight and activate Check button):
![6_1_fixed_two](https://user-images.githubusercontent.com/13650180/27302487-7d8cf2e4-54f4-11e7-841a-a1d3ef1558ea.png)

Correct answer on 2nd attempt (Feedback is strange as previous answer was flagged incorrect but is now flagged correct):
![6_1_finished](https://user-images.githubusercontent.com/13650180/27302516-966ddd64-54f4-11e7-86ed-c22e54c5a057.png)

**Comment by jonathanolson** [comment]
Sorry, had a bug that prevented this from happening. Should work now.

**Comment by amyh-phet** [comment]
Much better!  Still wondering if we should be flagging both answers as incorrect if a user accidentally enters one correct factor in both edit boxes.  I've asked @phet-steele to take a look and give some feedback.

**Comment by amyh-phet** [comment]
@jonathanolson   After discussing with @phet-steele, we both think it seems strange for both answers to be highlighted as incorrect if a user accidentally enters one correct factor in both edit boxes as in this example.
![6-1v](https://user-images.githubusercontent.com/13650180/27654318-1be00812-5bff-11e7-8569-0d7799b80116.png)

It seems strange that editing one box then automatically makes both answers correct.
![6-1v_correct](https://user-images.githubusercontent.com/13650180/27654346-2ec2686c-5bff-11e7-9c86-006fa129eef0.png)

I think it would be better to choose one of the factors to flag as incorrect and one factor could be marked correct.  While this means we arbitrarily will choose which answer is correct, it seems better than flagging a correct factor as incorrect.

**Comment by jonathanolson** [comment]
Implemented (and the "arbitrary" side can be either vertical or horizontal, but stays the same for the challenge).

The only weird bit is if (for example):

- The user selects 4,4 as their values (say 4,6 are the answers). We highlight the second 4 as wrong.
- The user changes the first 4 (that wasn't highlighted as wrong).

In this case, the logic removes the "error" highlight on the second 4 immediately, no matter what the new other value is. If they switch it to (6,4) then this makes sense (they didn't change the "wrong" one but it's consistent now).

Let me know how it looks.

**Comment by amanda-phet** [comment]
I like how this is working. I am glad only one answer is highlighted as wrong in the example of entering 4,4 when the correct answer is 4,6, and the logic to remove the error highlight is working well for me.
