### ISSUE TITLE
[Game] Level action prompts

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/area-model-common#43]
To be displayed in the game's status bar. Noting here so I can remove it on my internal TODO list.

**Comment by amyh-phet** [comment]
@jonathanolson    Here's what I have for Level action prompts:

Three possible things for users to complete.

Total area:
- Find the the total area.

Partial Product:
- Find the partial product.

Height or length:
- Find the side length.


If more than one answer is required on a challenge, then the prompt will include all relevant missing items.  For example, on the Numbers challenges:
2-1  Find the partial products.
2-2   Find the partial product and total area.

**Comment by jonathanolson** [comment]
Ended up with the following prompts, let me know how it looks:

```
  "levelPrompt.totalArea": {
    "value": "Find the total area."
  },
  "levelPrompt.oneProduct": {
    "value": "Find the partial product."
  },
  "levelPrompt.twoProducts": {
    "value": "Find the partial products."
  },
  "levelPrompt.oneProduct.totalArea": {
    "value": "Find the partial product and total area."
  },
  "levelPrompt.oneProduct.oneLength": {
    "value": "Find the partial product and side length."
  },
  "levelPrompt.twoLengths": {
    "value": "Find the side lengths."
  },
  "levelPrompt.threeLengths": {
    "value": "Find the side lengths."
  }
```

And yes, twoLengths and threeLengths are different string keys (Slovenian and https://en.wikipedia.org/wiki/Dual_(grammatical_number))

**Comment by amyh-phet** [comment]
Prompts look great.
