### ISSUE TITLE
[Game] End of level buttons

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/area-model-common#44]
I don't recall if this was decided in our meeting.

Should I implement some form of "Start level over" and "Go back to level selection" buttons instead of a single innocuous "next" button?

**Comment by amyh-phet** [comment]
@jonathanolson    I'd like to implement an end of level similar to what we have in many of our games.  Balancing Chemical Equations is a good model.  After completing the 6 challenges a level summary screen appears.  The score is summarized and and a Continue button is used to go back to the level selection screen.

![end_of_game](https://user-images.githubusercontent.com/13650180/27057934-89574a20-4f8b-11e7-87a8-8490eef15fba.png)

I'll work on a mockup and specifications for feedback given based on score.

**Comment by amyh-phet** [comment]
Here's  a mockup of what I'm thinking for the end  of level screen.   
![end_of_level](https://user-images.githubusercontent.com/13650180/27060318-2fe8f124-4f99-11e7-9d36-644254cc2274.png)

The prompt would change based on user score.

Score                    Prompt
0-5                        Keep trying
6-9                        Good!
10-11                    Great!
12                         Excellent!

**Comment by jonathanolson** [comment]
Should definitely be easy to do the "rains" effect. Will plan to handle tomorrow.

**Comment by jonathanolson** [comment]
Implemented. There's a common type for that "level completed" view that I'm using, but it is customizable some if you want changes. Let me know how it looks (and the transitions to the "end" and transitions to level selection and when the level is re-opened).

**Comment by amyh-phet** [comment]
Looks great to me.  I'll leave open to get comments from design team, but happy with current implementation for interviews.

**Comment by amanda-phet** [comment]
I completed level 1-1 to get the reward screen, and I'm not sure if it's my connection, but I heard the woohoo+clapping before I ever clicked "next" and saw the panel with the "continue" button. It seems like the panel should automatically pop up with the sounds. 

Otherwise, I like the way it looks!

**Comment by jonathanolson** [comment]
Assigned to myself, I don't believe I moved the sound over to when the "level complete" is shown.

**Comment by jonathanolson** [comment]
Fixed the sound timing.

**Comment by amyh-phet** [comment]
Looks and behaves as expected.  Closing
