### ISSUE TITLE
Replace double-line option

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/area-model-common#47]
Single line, half tick, increase both font sizes, move lines closer to area where appropriate.

**Comment by jonathanolson** [comment]
Also, should the placement of the partition size labels in the game change at all?

**Comment by jonathanolson** [comment]
Game labels currently unchanged. How does this look? (Half tick is hard to see, may want to try full tick).

**Comment by ariel-phet** [comment]
I personally think it looks great, and I think the half tick is enough. Very clean.

**Comment by amyh-phet** [comment]
@jonathanolson    I like the new font sizes, bold font, and half tick mark.  I'd like to see what it looks like with the following modifications:

- Make the dimension line thinner (back to the weight it was originally).

- Move the dimension lines and all numerical values closer to the model.  The blue height information seems especially far from the model.  Is there a way to move things in closer while still allowing for the display of factors on the screen?    I've tried to do a quick mockup of this, but let me know if you need better info to implement.
![current_implementation](https://user-images.githubusercontent.com/13650180/27053582-06bb3e4c-4f7b-11e7-9152-db29828947ae.png)
![dimension_lines_closer](https://user-images.githubusercontent.com/13650180/27053583-06c91274-4f7b-11e7-9eae-c5500f2d3981.png)

**Comment by jonathanolson** [comment]
I've made the line width change.

I hadn't moved the lines closer for two main reasons (each has a way I can compensate):

1. There's not much room in the generic view. **Is it acceptable to have the dimension line and erase button locations be different on generic/game screens?**
![generic-1](https://user-images.githubusercontent.com/480878/27072795-dbf3bd9c-4fde-11e7-86f0-19af2d62c6a5.PNG)

2. I'll need to go back to shifting some product labels vertically because they would overlap with the blue height labels. **Is it acceptable to do this, particular if needed on the Explore screen when it otherwise wouldn't be?**
![decimals-1](https://user-images.githubusercontent.com/480878/27072855-0964e594-4fdf-11e7-9fad-bed6f91d89cc.PNG)

Let me know if it should be done (with those additional changes), as it's a refactor I'd rather avoid if the above issues disqualify it from consideration.

**Comment by amyh-phet** [comment]
@jonathanolson   Let's hold for now and see if there is confusion in interviews.  We can always rehash this in design meeting on Thursday, but KP is the one who requested this change, so we will need to discuss further before deciding not to implement.

**Comment by amyh-phet** [comment]
@jonathanolson   I do think we need to move the blue numbers for partitioned height closer to the model.  The red numbers above seem to not cause confusion, but students weren't recognizing the blue numbers refer to partitioned lengths on the model.  In reference to your points above:

1)  I don't see a problem with the dimension line and erase buttons being in different locations on the Explore and Generic/Variables/Game screens.

2) Shifting product labels is okay when needed to avoid overlap with blue numbers.  

So to make you refactor...

**Comment by jonathanolson** [comment]
Should be done, let me know how it looks.

**Comment by amanda-phet** [comment]
This is looking good to me. I like the distance much better!

I noticed that the partial product labels shift out of the way if they are going to interfere with another label, as seen here:
<img width="429" alt="screen shot 2017-06-22 at 10 31 37 am" src="https://user-images.githubusercontent.com/7852916/27553229-5d0363c8-5a67-11e7-8afe-e56c1ec97e28.png">


Can you do the same thing on the decimals screen? It seems like they should shift out of the way in this case:
<img width="435" alt="screen shot 2017-06-22 at 10 33 04 am" src="https://user-images.githubusercontent.com/7852916/27553226-57b96502-5a67-11e7-9423-9a56a6afbd19.png">


And just to clarify, we decided to ignore this sort of scenario because the user should be using a smaller board, right? 

<img width="422" alt="screen shot 2017-06-22 at 10 33 54 am" src="https://user-images.githubusercontent.com/7852916/27553223-52798586-5a67-11e7-9441-6bd05fcf6f13.png">

**Comment by amyh-phet** [comment]
@amanda-phet    I agree that the factors should shift on the partial products you showed for the Decimals screen in the second screenshot above.  I do think we will have to live with some overlap on Decimals, especially when the user might build something on the 2x2 or 3x3 scene that is better visualized on the 1x1 scene.  I'll make a note of this for the Teacher Tips.

**Comment by jonathanolson** [comment]
> Can you do the same thing on the decimals screen? It seems like they should shift out of the way in this case:

They are on my devices that I've tested on:
![area-overlap](https://user-images.githubusercontent.com/480878/27759901-5f66c0b2-5df8-11e7-8b5c-c7825db3f3fb.PNG)

Can you recheck (just in case), and let me know more information about your computer/browser?

If it helps for comparison, the numbers indicate that on the decimals 1x1, the partial product labels on the left would be bumped up (to avoid the partition size label) when it meets or exceeds ~0.014 of the model units, which definitely seems to be happening in your screenshot.

**Comment by amanda-phet** [comment]
I just checked this on https://www.colorado.edu/physics/phet/dev/html/area-model-multiplication/1.0.0-dev.17/area-model-multiplication_en.html (I couldn't find the Area Model Decimals sim). It appears to be functioning as expected. 

![screen shot 2018-01-29 at 1 49 55 pm](https://user-images.githubusercontent.com/7852916/35533605-4d837fde-04fb-11e8-829e-791972e84b6d.png)
