### ISSUE TITLE
Reset all button breaks 2x2 display on Generic and Variables screen

### ISSUE THREAD

**Issue by amyh-phet** [phetsims/area-model-common#51]
When on the 2x2 model display, pressing the Reset All button changes the model to a 1x1 grid but does not update the readout on the model select drop down menu.

2x2 before pressing Reset All

![2x2_before_reset_all](https://user-images.githubusercontent.com/13650180/27055883-20739b1a-4f83-11e7-924f-bfaa349f0b75.png)
2x2 after pressing Reset All
![2x2_after_reset_all](https://user-images.githubusercontent.com/13650180/27055888-24e74804-4f83-11e7-834c-aeb6d6226661.png)

**Comment by jonathanolson** [comment]
Should be fixed, sorry about that!

**Comment by amyh-phet** [comment]
Fixed. Closing.
