### ISSUE TITLE
[Game] Randomize user inputs on challenge prompts in game

### ISSUE THREAD

**Issue by amyh-phet** [phetsims/area-model-common#52]
Is it possible to randomize which partial products or partitioned heights/lengths are presented on a challenge prompt?  

For example, in Variables 4-1, the two editable values should be randomly chosen from the 4 partitioned lengths.   This change would effect many challenges across all levels of both Number and Variables.  If this is possible, I can provide a list of challenges that would need to be randomized.

**Comment by jonathanolson** [comment]
Didn't see a response in Skype, but I'm curious about the type of randomization (which it will definitely be possible).

Is it the type of randomness where it's easy to just say "pick X of any Y", or does it need to be somewhat more structured and enumerated (like partial products can only be opposite, not on the same row/column)?

So for Variables 4-1, I really don't understand the proposal to randomly choose 4 partitioned lengths, as the pattern of which partial products are dynamic assumes a specific pattern of partition sizes being editable. Notably, if a partial product is dynamic but not in a row/column of any editable partition size, it would always look filled in.

**Comment by amyh-phet** [comment]
On Variables 4-1, the challenge currently has the user enter x for both partitioned lengths.  We'd like to have the user entering more than x for this challenge.  I recognize the challenge seems really easy as the dimension line lengths are given already, but mixing up which value to enter was a behavior we were looking for in this prompt.  I'm assuming it only gets more complicated if we tie which partial products are dynamic to a randomly set as well.   For 4-1, we could alternate between what we currently have (edit boxes on T and L) with edit boxes on B and R to add a bit of variety and to make sure dynamic partial products remain dynamic.

**Comment by amyh-phet** [comment]
**Easier challenges to randomize (I hope):**

- Numbers 1-2, 1-4,1-6 and Variables 1-1, 1-3: Pick any 1 product to be EDITABLE.

- Numbers 2-1, 2-3, 2,5 and Variables 2-1: Pick any 2 products to be EDITABLE.

- Numbers 2-2, 2-4 and Variables 2-2: Pick any 1 product to be EDITABLE (in addition to total area).

- Numbers 3-2 and Variables 3-1: Pick 1 of 2 horizontal lengths to be EDITABLE

- Numbers 3-4 and Variables 3-4: Pick 1 of 3 horizontal lengths to be EDITABLE.

- Numbers 3-1:  Pick 1 of 2 partial products to be DYNAMIC

- Numbers 5-1 and Variables 5-1: Choose 1 of 2 horizontal lengths to be EDITABLE

- Numbers 5-3 and Variables 5-2: Choose 1 of 3 horizontal lengths to be EDITABLE

- Numbers 6-1: Choose 1 of 2 vertical lengths to be EDITABLE.


**More complicated randomizations:**
-Numbers 3-3: Pick 2 of 3 horizontal lengths to edit.  This would require dynamic partial products to change based on which horizontal lengths are editable.

- Numbers 4-5:  Alter horizontal and vertical lengths to edit.  Products would not be impacted if:
products [GIVEN, DYNAMIC, GIVEN
               [GIVEN, GIVEN, DYNAMIC]
               [DYNAMIC, GIVEN, GIVEN]



3 options for 4-5:   
horizontal [EDITABLE, GIVEN, GIVEN]
vertical [EDITABLE, EDITABLE, GIVEN]

OR

horizontal [GIVEN, EDITABLE, GIVEN]
vertical [GIVEN, EDITABLE, EDITABLE]

OR
horizontal [GIVEN, GIVEN, EDITABLE]
vertical [EDITABLE, GIVEN, EDITABLE]

- Variables 3-3: Choose 1 of 2 horizontal lengths to be EDITABLE.  This would impact which product would be DYNAMIC.

Options:
horizontal [EDITABLE, GIVEN]
vertical [GIVEN]
products [GIVEN, EDITABLE]

OR 
horizontal  [GIVEN, EDITABLE]
vertical [GIVEN]
products [EDITABLE, GIVEN]  

- Variable 3-5; Choose 2 of 3 horizontal lengths to be EDITABLE.  This would impact which product is DYNAMIC (would need to be in an EDITABLE horizontal column).  I can spell out options as for Variables 3-3 if needed.

- Variables 3-6:  Choose 1 of 3 horizontal lengths to be EDITABLE.  Again, impacts products; EDITABLE product would need to come from a different column.

**Comment by jonathanolson** [comment]
What times do you have available to discuss over Skype?

**Comment by amyh-phet** [comment]
In addition to the list above to randomize editable areas in problems, it would be nice to implement changes to the following challenges.  This will also address some of the issues we had with oddly chose dynamic products.

**Numbers:**
Change the following challenges:
- 4-2
horizontal [GIVEN, EDITABLE, EDITABLE]
vertical [EDITABLE, GIVEN]
products [GIVEN, DYNAMIC, GIVEN]
               [GIVEN, GIVEN, DYNAMIC]

- 4-3
horizontal [EDITABLE, EDITABLE, GIVEN]
vertical [GIVEN, EDITABLE]
products  [DYNAMIC, GIVEN, GIVEN]
                [GIVEN, DYNAMIC, GIVEN]


**Variable**
Add the following challenges:

- 4-3
horizontal  [GIVEN, EDITABLE]
vertical [GIVEN, EDITABLE]
products [GIVEN, DYNAMIC]
               [DYNAMIC, GIVEN]

- 4-4
horizontal [GIVEN, EDITABLE]
vertical [GIVEN, GIVEN]
products [GIVEN, GIVEN]
                [EDITABLE, GIVEN]

**Comment by amyh-phet** [comment]
Currently sitting in on an accessibility meeting.  Let me ping Ariel and see if it's okay to talk with you instead.  Otherwise I'm available after 12 pm.

**Comment by amyh-phet** [comment]
Ready to discuss when you are.  Feel free to call over skype when ready.

**Comment by amyh-phet** [comment]
Looks like this is working properly now.
