### ISSUE TITLE
[Game] Exclude 1 from prompts that include multiplication by a single digit

### ISSUE THREAD

**Issue by amyh-phet** [phetsims/area-model-common#53]
For Challenges that include a single digit number, exclude the number 1 on the single digit side (e.g. prevent a user from getting a challenge such as 51x1).

Challenges that would be impacted:
Numbers:  1-1, 1-2, 1-3, 1-4, 3-1, 3-2, 3-3, 3-4, 5-1, 5-3
Variables: 1-1, 1-2, 1-3, 1-4, 3-1, 3-2, 3-3, 3-4, 3-5, 3-6, 5-1, 5-2

**Comment by jonathanolson** [comment]
Implemented (assuming -1 is ok for variables challenges), let me know if that looks ok.

**Comment by amyh-phet** [comment]
Looks good.  Yes a -1 is fine on the variables challenges. Closing.
