### ISSUE TITLE
[Game] Clear dynamic updates if user input is incorrect

### ISSUE THREAD

**Issue by amyh-phet** [phetsims/area-model-common#55]
If user enters incorrect values on challenge which includes dynamical values, and then presses Check button dynamic values should clear when feedback about incorrect answer is given.

**Comment by jonathanolson** [comment]
Implemented, 'error' highlighted values act like empty values as far as dynamic displays are concerned now.

**Comment by amyh-phet** [comment]
@jonathanolson   Again, my apologies as I wasn't specific enough with an earlier request.  Current implementation looks good for behavior after first and second incorrect attempts.  When user clicks on Show Answer button, correct answer should appear on dimension lines and in Product panel.  

Initial problem:
![6-1_n_initial](https://user-images.githubusercontent.com/13650180/27103736-ee87a276-5046-11e7-9dc4-ce730bfa3438.png)

After 2nd incorrect answer
![6-1-n-2nd_incorrect_answer](https://user-images.githubusercontent.com/13650180/27103757-fe00c41c-5046-11e7-9e3d-a78ed1f287b7.png)

After clicking Show Answer button:
![6-1-n-show_answer](https://user-images.githubusercontent.com/13650180/27103770-0ab09d5e-5047-11e7-81b8-e670ab787e7e.png)

Can we implement this instead for what would be displayed after clicking Show Answer (assuming the Check button would be a Next button)
![6-1n_preferred_display_show_answerr](https://user-images.githubusercontent.com/13650180/27103797-246b34ca-5047-11e7-927a-0079812edcb1.png)

So 99 would appear along the dimension line and in the Product panel.

**Comment by jonathanolson** [comment]
Implemented, can you check?

**Comment by amyh-phet** [comment]
Behavior is consistent with what I expected.  Closing.
