### ISSUE TITLE
[Game] Variables 1-1 and 1-3 make product editable text box handle 2 digits with or without negatives

### ISSUE THREAD

**Issue by amyh-phet** [phetsims/area-model-common#57]
On some Variables challenges, the edit boxes for entering partial products are constrained to entering only one digit (with or without negative sign).   This makes it impossible to enter a correct answer for the partial products.
Problems effected:
Variables 1-1 - right edit box
![1-1_edit_box_too_small](https://user-images.githubusercontent.com/13650180/27105847-4a80247a-504e-11e7-8761-7750851c3e15.png)
Variables 1-3 - middle and right edit boxes
![1-3_edit_box_too_small](https://user-images.githubusercontent.com/13650180/27105848-4a806d0e-504e-11e7-8946-6632a2ace722.png)

Other challenges with similar issues:
Variables 2-2 - bottom right edit box
Variables 3-3 - right edit box for partial product
Variables 3-6 - middle and right edit box for partial product
Variables 4-2 - bottom right edit box for partial product

**Comment by jonathanolson** [comment]
It looks like the number of allowed digits was always 1 (incorrectly). It should be 2, and I've fixed it in code. Can you verify?

**Comment by amyh-phet** [comment]
Verified as fixed.  Closing.
