### ISSUE TITLE
No error highlighting for editable polynomial total area

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/area-model-common#59]
Feels weird, I'd prefer if it had something with the equivalent colors for other edit boxes.

Thoughts?

**Comment by amyh-phet** [comment]
After the first interview today, I definitely think we need some color cues here so 
1) User know they have to use the spinners to edit (a student didn't realize she needed to interact with the spinners until she got the challenge wrong)

2) User didn't know why the answer was wrong as she had also entered a partial product and the partial product was correct.

What if the spinners started out as light blue (like in Graphing Lines) and then turned the same color red as we use for incorrect answers with edit boxes?

**Comment by jonathanolson** [comment]
> What if the spinners started out as light blue (like in Graphing Lines) and then turned the same color red as we use for incorrect answers with edit boxes?

Sounds good. Can we use the same light blue for the other edit boxes as well, for the same state?

**Comment by amyh-phet** [comment]
Yes, let's try that.

**Comment by jonathanolson** [comment]
Implemented. For now, the highlight affects all of the number pickers.

It feels a bit weird that editing one brings all of the highlights away from the error/input-needed state. However if one value SHOULD be zero, we wouldn't want to require it be changed.

Thoughts?

**Comment by amyh-phet** [comment]
I'll play with it a bit today and see how it feels.   I'll discuss with @amanda-phet on Monday to see if we need to change implementation.

**Comment by amyh-phet** [comment]
@jonathanolson    I like the blue highlighting to help users know to use the spinners.  The red error cues are good too, but I think that we need to find a way to only highlight the incorrect entry.   Here's what I'd propose:

1) Spinners start out blue as in current implementation.
2) Spinners change to black when user has entered a value. The spinner remains blue if the coefficient/constant should be zero.
3) When user presses Check button, only the incorrect spinner values turn red.  The remaining spinner values stay black.

Is this behavior a possibility?

**Comment by jonathanolson** [comment]
Should be possible, I'll get it done.

**Comment by jonathanolson** [comment]
This should be implemented, sorry about the delay. It kind of ended up breaking a few core assumptions in the game (fixed now).

> Spinners change to black when user has entered a value. The spinner remains blue if the coefficient/constant should be zero.

I interpreted this as "if the correct value is 0, the spinner will be blue whenever it is not 0".

Let me know if this all looks good (or if you notice any bugs elsewhere in the game).

**Comment by amyh-phet** [comment]
@jonathanolson    Looks good to have the spinners highlight independently.  When testing this, I couldn't get the Check button to activate.

**Comment by jonathanolson** [comment]
Looks like I didn't fully test polynomials where there are only two spinners, I'll get this fixed.

**Comment by amyh-phet** [comment]
@jonathanolson    I also realize I didn't elaborate enough when describing the change of colors when spinners are used.  Here's a second try to explain the desired behavior.

1) Spinners function independently of one another.
2) Spinners all start with blue highlight and 0 in the display.
3) Any user interaction with the spinner results in the blue highlight changing to black.
4) If user does not interact with the spinner, the blue highlight remains.
5) Check button becomes active once at least one spinner has been changed.

**Comment by jonathanolson** [comment]
Implemented, let me know how it looks.

**Comment by amanda-phet** [comment]
This is functioning as intended.
