### ISSUE TITLE
How to treat 0x or 0x^2?

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/area-model-common#6]
If the user enters that in the keypad, do we treat it as 0x or 0x^2 (very possible to do), or just treat it as 0?

**Comment by jonathanolson** [comment]
And if we treat it as 0x, when would this be simplified out in the area model calculation for variables?

**Comment by amyh-phet** [comment]
I would lean toward treating it as 0. @amanda-phet  can you weigh in here as you have better insight to this question pedagogically.

**Comment by amanda-phet** [comment]
I would leave it as 0. There are other cases where what they user enters on the keypad might be displayed differently, such as entering 'x2' and displaying it as '2x'. Is there a general way to describe how/when to simplify? We should think about that. But 0x should simplify to 0.

**Comment by amyh-phet** [comment]
I can think of three cases to simply:
1) Entering a zero as the first digit in a number value.  In this case, the zero would be removed (e.g. entering 012 would simply to 12).
2) Entering a zero before a variable entry (either 0x or 0x^2). Entry would be simplified to 0 in both cases.
3) Entering a variable before a coefficient (either x6 or x^2 6).  Entry would be simplified to show the coefficient before the variable (eg. x6 would be simplified to 6x and x^2 6 would be simplified to show 6x^2.

**Comment by amanda-phet** [comment]
4. x0 would simplify to 0 (combination of 2 and 3 above) 

Do you remember the discussion about xx? Is it even a possibly entry?

**Comment by amyh-phet** [comment]
xx is not a possible entry.  User can only enter x or x^2 once at which point the keypad prevents additional entries of variable.  We did this as simplifying xx was problematic.

**Comment by jonathanolson** [comment]
Implemented.
