### ISSUE TITLE
Make partition drag handles triangles instead of circles

### ISSUE THREAD

**Issue by amyh-phet** [phetsims/area-model-common#61]
@jonathanolson  The one student I interviewed still didn't use the drag handle on the Explore screen even with the arrows.  Can we make the orange and blue circles into triangles instead?  I think we should still leave the arrows to cue movement.   
![triangle_partition_handles](https://user-images.githubusercontent.com/13650180/27299543-e752e694-54e9-11e7-8037-1541f70a2c07.png)

**Comment by jonathanolson** [comment]
Implemented, let me know how it looks.
