### ISSUE TITLE
Implement readout display for spinners on Variables Game screens

### ISSUE THREAD

**Issue by amyh-phet** [phetsims/area-model-common#62]
@jonathanolson    After conducting interviews, it's clear that students are struggling to interpret the expression for total area with the spinners.   I do think we will need to implement a readout box above the spinners in the Total area panel.  Two of the students were able to correctly complete the total area challenges if I wrote out the expression after they used the spinners.  They both were able to correct mistakes if they saw the information that would be displayed in the readout.
![total_area_panel_readout](https://user-images.githubusercontent.com/13650180/27302816-d275241a-54f5-11e7-9c60-c0602a422d87.png)

**Comment by jonathanolson** [comment]
Implemented.

It currently starts off as "0" due to the current implementation with the pickers. Should it start off as a "?" instead?

**Comment by amyh-phet** [comment]
Looks good.  I like zero as I think it better reflects what the spinner readouts say. I also want to avoid confusion with ? on the previous screens where the ? means the area is not yet defined.

**Comment by amyh-phet** [comment]
@amanda-phet    Can I get your thoughts on how the readout works for the Variables game?  This applies to challenges 1-2, 1-4, 2-2 on the Variables game.

**Comment by amanda-phet** [comment]
I really like how it is working!

**Comment by amyh-phet** [comment]
Implemented and looks good.  Closing.
