### ISSUE TITLE
Make editable partial products entry boxes handle larger than needed numbers on Game screen

### ISSUE THREAD

**Issue by amyh-phet** [phetsims/area-model-common#63]
@jonathanolson    Currently, user entries in edit boxes are limited on the Game screen, but I'm not sure how the limit is defined.  Is it possible to make the edit boxes accept an entry that is larger than the correct answer.  For example, if the correct answer is 450, could the edit box accept a 4 digit answer.  I'm thinking that extending the box by one digit would allow students to enter answers that they think are correct, then get feedback when the answer is not correct.

**Comment by jonathanolson** [comment]
Implemented (for numbers and variables challenges).

**Comment by amyh-phet** [comment]
Looks good. Closing.
