### ISSUE TITLE
Show Answer should fill in the ? terms

### ISSUE THREAD

**Issue by phet-steele** [phetsims/area-model-common#67]
<img width="1881" alt="screen shot 2017-06-22 at 2 06 32 pm" src="https://user-images.githubusercontent.com/5863899/27453573-29ad5f44-5754-11e7-92db-dca6fe8b347b.png">

**Comment by jonathanolson** [comment]
Applied fix, can you verify?

**Comment by phet-steele** [comment]
Verified, gracias.
