### ISSUE TITLE
Cuing arrows on partition drag handles should be visible until partition is moved

### ISSUE THREAD

**Issue by amyh-phet** [phetsims/area-model-common#68]
With current implementation, cuing arrows disappear once a user has clicked on a drag handle.  Several users clicked on drag handle, dismissed cuing arrows, but never moved drag handles in interviews.    The cuing arrows should persist until the user drags the handle and moves a partition line.

**Comment by jonathanolson** [comment]
Implemented, let me know how it looks.

**Comment by amanda-phet** [comment]
This is working well.
