### ISSUE TITLE
Always display factors as height x width

### ISSUE THREAD

**Issue by amyh-phet** [phetsims/area-model-common#69]
Current implementation shows factors for areas that are perfect squares as exponents (e.g. 10^2).  This was confusing to younger students in interviews. Change factors to show height x width (e.g. 10 x 10) instead.
  
This change applies to all screens with numbers (Explore, Generic, Decimals)
![2017-06-28_1414](https://user-images.githubusercontent.com/13650180/27658131-34ab501a-5c0c-11e7-978b-1eab5b562cfe.png)

**Comment by jonathanolson** [comment]
Implemented, let me know how it looks.

**Comment by amanda-phet** [comment]
I think this is fine.
