### ISSUE TITLE
Potentially coloring the partial factors readouts?

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/area-model-common#7]
In each partitioned area, with "partial products" set to "factors", I think it might be helpful to color the width and height (so it is obvious which one is the width and which is the height). Would that add to the sim, or take away from it?

**Comment by amyh-phet** [comment]
i think this is a good topic for discussion at design meeting.  In looking over meeting notes, I don't think we discussed if using this type of mapping would be beneficial or give away too much information.

**Comment by amyh-phet** [comment]
Discussed at design meeting on 5/11/17.  Decision made to not color factors on model.  Concerned that it will add additional visual weight to sim and detract from the color mapping already present.
