### ISSUE TITLE
Change default settings on Explore Screen

### ISSUE THREAD

**Issue by amyh-phet** [phetsims/area-model-common#70]
Because most users did not use the partition lines on the Explore screen during interviews, we need to better cue why users would want to use these tools.  Changing the default for the Explore screen will hopefully address these issues.  

For both scenes:
- Total area panel is open
- Products button (A) is selected in the Partial products panel 
- Cuing arrows for partition line drag handles are visible for both drag handles and remain visible until user drags handle.

For 20x20 scene:
- Gray rectangle is initially 10 x 10
- Blue partition line is used to divide height into 5, 5.
![20x20_default](https://user-images.githubusercontent.com/13650180/27661233-c4e6c51a-5c16-11e7-8aa2-e923905393e7.png)

For 100x100 scene:
Gray rectangle is initially 50 x 50
- Blue partition line is used to divide height into 30, 20.
![100x100_default](https://user-images.githubusercontent.com/13650180/27661269-dedc0e08-5c16-11e7-9e94-07550ff2ff2b.png)

**Comment by jonathanolson** [comment]
Implemented, let me know how it looks.

**Comment by amanda-phet** [comment]
Looks good. Closing.
