### ISSUE TITLE
Display multiplication with a multiplication sign (x) on Explore and Decimals screen

### ISSUE THREAD

**Issue by amyh-phet** [phetsims/area-model-common#71]
Younger users had trouble interpreting the calculation panel during interviews as they were not familiar with the use of parentheses to indicated multiply.

The calculation panels for both the Explore and Decimals screens should use a multiplication sign (x) instead of parenthesis to indicate when terms are being multiplied.

Mockups show all lines of the calculation for reference.
![explore_calculation_panel](https://user-images.githubusercontent.com/13650180/27661605-2a55e510-5c18-11e7-97db-979495606b95.png)
![decimals_calculation](https://user-images.githubusercontent.com/13650180/27661609-2d99ae5a-5c18-11e7-9295-0e1423b13758.png)

**Comment by amanda-phet** [comment]
Just to clarify, we should be using the unicode symbol for multiplication:

<img width="122" alt="screen shot 2017-06-29 at 10 55 54 am" src="https://user-images.githubusercontent.com/7852916/27700030-90d37ac2-5cb9-11e7-961e-17a68bd203f9.png">

**Comment by jonathanolson** [comment]
Implemented, let me know how it looks.

**Comment by amanda-phet** [comment]
This is looking good to me.
