### ISSUE TITLE
Display multiplication with a dot in the calculation for the Generic screen

### ISSUE THREAD

**Issue by amyh-phet** [phetsims/area-model-common#72]
To help younger students access the calculation information on the generic screen, we need to use something other than parentheses to show multiplication.  Use of a dot to signify multiplication on this screen transitions away from using an x to indicate multiplication while still using a symbol that younger users will recognize as indicating multiplication.  

![generic_calculation](https://user-images.githubusercontent.com/13650180/27661774-d3f6f514-5c18-11e7-96d7-3bc4f8141097.png)

**Comment by jonathanolson** [comment]
Initial implementation, some notes:

I'm using the unicode dot operator (preferred for multiplication), see http://www.fileformat.info/info/unicode/char/22c5/index.htm.

It looks nice with positive values:
![area-dot-positive](https://user-images.githubusercontent.com/480878/27759540-415043da-5df0-11e7-996f-8a40478253fe.PNG)

but would potentially need tweaks for negative values (hard for me to see clearly):
![area-dot-negative](https://user-images.githubusercontent.com/480878/27759542-4e314c66-5df0-11e7-992d-91b45ccfc551.PNG)

and it is much smaller than the mock-up above.

I could replace this with just a colored circle that is larger, but it would presumably not auto-adjust to the vertical level of the other operators in each font.

Thoughts?

**Comment by amanda-phet** [comment]
Is space a constraint? I'm wondering why we can't use the same symbol in https://github.com/phetsims/area-model-common/issues/71. I am guessing it is space. 

I agree the dot isn't working that great here. I'm also concerned about using an x, •, and () all within one sim (Algebra). I wonder if we should instead use an x in the Introduction sim, • in the Multiplication sim, and () in the Algebra sim, so at least within a single sim we are being consistent.

**Comment by amanda-phet** [comment]
@kathy-phet and I discussed this and would like to first try the following: Can we still use the unicode symbol, but try making it bold, or a larger font? We'd like to try going that route before drawing a circle. 

If that doesn't work, then I will specify which symbols to use in which screens without using a dot at all.

**Comment by jonathanolson** [comment]
How does bold look:

![area-model-bold-dot](https://user-images.githubusercontent.com/480878/36002756-89b55834-0ce8-11e8-8c92-b8cb0541e736.PNG)

**Comment by kathy-phet** [comment]
Seems better. Is it possible to put a small bit of white space around the dot, it is looking pretty compact and might be better to set it apart? Like a 1/4 of a space in front and back of the dot?

**Comment by jonathanolson** [comment]
Is this sufficient:

![area-model-bold-dot-2](https://user-images.githubusercontent.com/480878/36003764-a0e4d2ba-0cec-11e8-9c6d-113a7ec4be50.PNG)

**Comment by jonathanolson** [comment]
(that is 2 units of space more around every side of a dot).

**Comment by kathy-phet** [comment]
JO, I think that looks better, but to me it looks like more space got put in front of the dot than after the dot? Is that just my imagination?

**Comment by jonathanolson** [comment]
> JO, I think that looks better, but to me it looks like more space got put in front of the dot than after the dot? Is that just my imagination?

It's weird, I noticed that in some cases, and checked the code. I'll triple-check, but I think it is actually increasing the spacing in both equally, but pixel snapping (that SVG might be doing with text) might be slightly altering the end effect. The right-most dot and a few others seem more balanced. I agree that some (-99 . -999) definitely looks unbalanced, and I'll look into it.

**Comment by kathy-phet** [comment]
I checked it out on phettest and it looked good to me.

**Comment by amanda-phet** [comment]
The dot looks OK to me. The last thing I want to discuss is when to use the dot. On the Generic screen the partial products are displayed as axb but the calculation is displayed as a•b. In the variables screen, the partial products and calculation are both displayed as (a)(b) and in the Explore screens both are displayed as axb. So, in other screens there is consistency between the partial products on the model and in the calculation. 

Should we display the partial products with a dot for added consistency?

**Comment by amanda-phet** [comment]
OK, here is what I think is the best final decision. This applies to both the partial product displays, partial product radio button, and calculation panels. 

|  | Representation | Notes |  
|---|---|---|
| **Partition** | x |  no change |  
| **Explore** | x | no change |  
| **Generic** | • | no change to calculation </br> update partial products and radio button to use • |  
| **Variables** | • | change calculation, partial products, and radio buttons to use • in same way as Generic screen | 

I've summarized all screens that have a calculation panel because I want it all in one place, even though you are only changing the Generic and Variables screens. I looked into which representations are used at which grade levels, as well as considered consistency between and within sims. 

Let me know if anything needs clarifying! I've been thinking about this for a while so it all makes sense in my head, but might not to someone else :)

**Comment by jonathanolson** [comment]
Implemented the in-person-described changes, can you confirm in master?

**Comment by amanda-phet** [comment]
Looks great. 

Decision was to not use a dot at all, and just use the x everywhere except for the Variables screen.
