### ISSUE TITLE
Change default settings on Decimals screen

### ISSUE THREAD

**Issue by amyh-phet** [phetsims/area-model-common#73]
Because users did not explore with partitions, let's try a new default setting to make the partitions more visible.
1x1 scene
![1x1_default_001](https://user-images.githubusercontent.com/13650180/27705896-ba0e057a-5ccc-11e7-98e8-fe9b7c982fdd.png)

2x2 scene
![2x2_default_001](https://user-images.githubusercontent.com/13650180/27705904-c1385c10-5ccc-11e7-99e6-6d411e4d443a.png)

3x3 scene
![3x3_default_001](https://user-images.githubusercontent.com/13650180/27705910-c800d2ac-5ccc-11e7-9bb6-8b058b0446db.png)

**Comment by jonathanolson** [comment]
Implemented, let me know how it looks.

**Comment by amanda-phet** [comment]
This looks good so I think we can close this issue.
