### ISSUE TITLE
filename prefixes don't follow PhET conventions

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/area-model-common#76]
The convention for filename prefixes is to use either the full name of the repository, or the abbreviated acronym for the repository. E.g for expression-exchange, we would have either ExpressionExchangeConstants.js or EEConstants.js. The choice is up to the developer, should be applied consistently, and should not duplicate an abbreviation that is already used by another repository.

area-model-common uses "AreaModel" as a prefix, which doesn't follow either convention.

**Comment by jonathanolson** [comment]
It seems to be a semi-convention for some common repos (see CircuitConstructionKitPanel and other examples in CCK).

"AreaModel" to me seems nicer than "AreaModelCommon" or "AMC". Perhaps we can discuss this at a developer meeting for what prefixes are allowed?

**Comment by jonathanolson** [comment]
As a side-note, I'd rather call "area-model-common" as "area-model" for a repository, if that would help things.

**Comment by pixelzoom** [comment]
Btw... This came up as the result of a Slack discussion (developer channel) that resulted in this addition to the code-review checklist: https://github.com/phetsims/phet-info/commit/1774711ac188089c7d414e6e295db149a1254ca0

**Comment by pixelzoom** [comment]
@jonathanolson said:
> Perhaps we can discuss this at a developer meeting for what prefixes are allowed?

Do you have a proposal?

**Comment by jonathanolson** [comment]
> Do you have a proposal?

I'm not sure about the best way to generalize it, but the "AreaModel" and "CircuitConstructionKit" prefixes seem nice to me (for those common repos). I'd like to hear others' thoughts.

**Comment by samreid** [comment]
Meeting consensus: common repos will end with "common", names will match repo names and it is developers to us to decide whether to use full name or standard abbreviations.

**Comment by jonathanolson** [comment]
Implemented for everything except `AreaModel` so far, as I'm curious what to call it. It's the base type for all models for area-model sims, so is `AreaModelCommonModel` the recommended name?

**Comment by samreid** [comment]
`AreaModelCommonModel` makes sense to me.
