### ISSUE TITLE
Change to "Total area of model" readout

### ISSUE THREAD

**Issue by amanda-phet** [phetsims/area-model-common#79]
In the Multiplication, Algebra, and Decimals flavors of this sim, we would like to have a similar readout that we have implemented in Introduction. 

This is a two-part request. 

1. Increase the font size slightly for the "Product" readout (The "Area = XX" text) in Introduction. Can you increase it 10-20%? I think you can decide what looks large enough to make a difference but also small enough to fit nicely. 
<img width="675" alt="screen shot 2018-02-01 at 10 52 48 am" src="https://user-images.githubusercontent.com/7852916/35694291-1fab6668-073e-11e8-925e-c0731015c678.png">

2. Change the "Total model of area" accordion box (in Multiplication, Algebra, and Decimals) to have a similar readout, but with a coordinating gray background instead of yellow. I think we should try the same size that we are using in Introduction after determining (1) above. 
<img width="677" alt="screen shot 2018-02-01 at 10 54 14 am" src="https://user-images.githubusercontent.com/7852916/35694336-3ee9272c-073e-11e8-95b5-64e8d4dcded2.png">

It's possible the size of the accordion boxes will increase but I think there is enough space below for other boxes to move down.

**Comment by jonathanolson** [comment]
On the Variables screen, I can make the total area "-81x^4 - 162x^3 - 243x^2 - 162x". It is actually currently buggy, but that may get scaled down fairly significantly. Is that a problem?

**Comment by jonathanolson** [comment]
Additionally, the rounded-rectangle background for the area value was created with the "maximum" size so that it wouldn't resize. Would we consider changing that so that it can update nicely? (Seems almost required for the Variables screen, and it would be nice to have it consistent).

I'd like to adjust the code so that it resizes with its content so we can see how it looks (and we can change it easily in the future if desired).

**Comment by amanda-phet** [comment]
I forgot about the Variables screen. On that screen, it seem more appropriate to drop the "Area =" part and just show "-81x^4 - 162x^3 - 243x^2 - 162x" in the gray rounded rectangle. And yes this is quite buggy right now... you can get up to 5 terms and it's only showing 4 right now. 
![screen shot 2018-02-01 at 1 18 25 pm](https://user-images.githubusercontent.com/7852916/35701158-64af25f6-0752-11e8-98f8-ac321bdc9feb.png)


>Additionally, the rounded-rectangle background for the area value was created with the "maximum" size so that it wouldn't resize. Would we consider changing that so that it can update nicely?

For each sim this seems like a good idea. Perhaps even each screen, since Variables needs something different than the previous screens. Can we have different sizes for different screens?

**Comment by amanda-phet** [comment]
@kathy-phet and I need to discuss each screen of all 4 sims. Hopefully we can discuss this Monday 2/5.

**Comment by amanda-phet** [comment]
Discussed this with @kathy-phet and we would like this change to only apple to screens with scaled models (Multiply, Partition, Explore, Decimals). @jonathanolson and I discussed this last Thursday as well so I am confirming that that makes the most sense. 

@jonathanolson let me know if we should discuss this some more. Can you also implement this before Friday so we can get this change in the next dev versions for interviews? I am interviewing on AM Introduction but may also show students AM Multiplication.

**Comment by jonathanolson** [comment]
Implemented, let me know how it looks.

**Comment by kathy-phet** [comment]
I think this looks good. 

@amanda-phet - I do have one more thought as I am playing, that I would like to advocate for. We discussed it briefly but the more I play, the more I think it would be good to have as the default.

**Comment by amanda-phet** [comment]
What is the thought you have? Can you include it here so we can specify the exact changes we want to see?

**Comment by kathy-phet** [comment]
It's issue #83 .

**Comment by amanda-phet** [comment]
OK, thanks for clarifying. 

Then @jonathanolson can you make this change? 

The total area readout should have a gray background not a yellow background for the Multiplication, Algebra, and Decimals sims.

**Comment by jonathanolson** [comment]
Implemented the fix, sorry about that!

**Comment by amanda-phet** [comment]
No worries. This is looking good now.
