### ISSUE TITLE
Handling of duplicate exponents

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/area-model-common#8]
I didn't see an example for the "Area model calculation" with variables where partitions had duplicate exponents, e.g. width partitioned into "2x", "-x" and "5". Would the first line have these remain separated e.g. "(2x - x + 5)", or should it be simplified first e.g. "(x + 5)"?

**Comment by jonathanolson** [comment]
Currently planning to initially implement so that it shows each partition (instead of combining) for the calculation. Also planning to keep whatever order the user enters variables in (so if 5 is on the left, and x is on the right, it would be "5 + x").

**Comment by jonathanolson** [comment]
On the other hand, the 1st screen has the steps:
```
7 x 14
(5 + 2)(10 + 4)
5(10) + 5(4) + 2(10) + 2(4)
```
so would that example with variables want an extra line to mimic, e.g.:
```
(7)(x + 5)
(7)(2x - x + 5)
(7)(2x) + (7)(-x) + (7)(5)
```

**Comment by amyh-phet** [comment]
@jonathanolson 

Your example above is the behavior we expected in the Area model calculation panel. 

So yes to this implementation:

(7)(x + 5)
(7)(2x - x + 5)
(7)(2x) + (7)(-x) + (7)(5)

I also agree that if a student enters a 5 in the left most (or top most box for height) and then a variable such as x in the middle or right most box, the order would be preserved (so 5 + x).

**Comment by jonathanolson** [comment]
Also, should that extra line only be added when two factors are combined in the sum? What about out-of-order factors?

For example:

- "2x + 5 - x" would have the extra line (top line would be `(x + 5)`, extra line would be `(2x + 5 - x)`.
- "5 + x" would (potentially?) have the extra line, since the top line would be `(x + 5)` (order of factors), and the extra line if it exists would be the reverse `(5 + x)` so the distribution occurs normally?
- "x + 5" would presumably NOT have the extra line (assuming the other dimension is something similar, since it would be a duplicate.

**Comment by amyh-phet** [comment]
Using your examples, I think we need an extra line when either two factors are combined in the sum or when we have out-of-order factors.  So yes, extra step for:

- "2x + 5 - x" would have the extra line (top line would be (x + 5), extra line would be (2x + 5 - x).

- "5+ x" would have the extra line, since the top line would be (x + 5) (order of factors), and the extra line if it exists would be the reverse (5 + x) so the distribution occurs in a way that matches the model

No extra line needed for "x+5" as you stated above.

**Comment by jonathanolson** [comment]
Thanks, will implement!
