### ISSUE TITLE
switch order of area model cal and partial products panels

### ISSUE THREAD

**Issue by amanda-phet** [phetsims/area-model-common#81]
When discussing tab navigation order for these sims I realized that the flow is really natural in the Introduction sim where the user turns on partial products before viewing the calculation panel. I think we should have the same flow in the other sims. 

So, for Multiplication, Algebra, and Decimals sims, the panels on the right should switch. 

@ariel-phet also mentioned the idea of combining them into one panel with a thin separator (like Projectile Motion) so the sim is less panel-y. 

Can we make this full change this week before Friday? If not, can we at least change the order of the panels?

![screen shot 2018-02-06 at 3 07 28 pm](https://user-images.githubusercontent.com/7852916/35886775-6878777c-0b4f-11e8-8636-d627dbbe5372.png)

**Comment by jonathanolson** [comment]
Implemented in master, can you check how it looks?

**Comment by amanda-phet** [comment]
This looks great to me! Thanks!
