### ISSUE TITLE
Should we be using math font?

### ISSUE THREAD

**Issue by amanda-phet** [phetsims/area-model-common#84]
In other newer math sims we are using an italic script font for the variable x. See Function Builder and Expression Exchange as examples. Ideally this is done everywhere, so we should explore doing it in this sim as well. All other fonts should look the same (PhET font is fine for numerals) but where you see x we should use this customization. 

The result should look something like this.
![screen shot 2018-02-09 at 2 11 56 pm](https://user-images.githubusercontent.com/7852916/36050283-2c351f76-0da3-11e8-80ee-f7d5bf51a7e9.png)

**Comment by jonathanolson** [comment]
Implemented (you'll want to pull scenery also if you test on phettest.colorado.edu)

**Comment by amanda-phet** [comment]
I checked dev.6 and it looks great!
