### ISSUE TITLE
Tweak to Area Model Introduction (Partition screen)

### ISSUE THREAD

**Issue by amanda-phet** [phetsims/area-model-common#85]
One student in interviews didn't find the partition radio buttons, and I think it was their location, because she fully explored the other controls on the right side of the screen. I also am not a huge fan of the style anyway, since we're using the "scene selection " style elsewherein the sim. 

Can we combine them with the partial products panel? I had to change their appearance slightly to fit the shorter button height, but I trust your judgement to make them however they look best. 
![screen shot 2018-02-16 at 11 31 30 am](https://user-images.githubusercontent.com/7852916/36329476-4d2d2d1a-1323-11e8-9d21-31269ccbdcb9.png)

**Comment by jonathanolson** [comment]
Implemented:
![area-model-partitions](https://user-images.githubusercontent.com/480878/36331723-369a19c4-132c-11e8-877c-c0f8690448cf.PNG)

Definitely up for visual changes. The "way things were done" default was to keep more padding (feels more consistent to me) and to keep the width of the choice buttons the same. Reduced height of the icons to compensate slightly.

It should be possible to change the size of the "rectangles" in the icons for each orientation (let me know). I don't think aligning top-left with the way I have it now looks good:
![area-model-top-left-alignment](https://user-images.githubusercontent.com/480878/36331767-6e01b00c-132c-11e8-9dd3-0d9ed53307ad.PNG)

**Comment by amanda-phet** [comment]
Discussed with @jonathanolson this morning and we centered the model in the radio button and played a bit with the size. 

![screen shot 2018-02-20 at 1 21 20 pm](https://user-images.githubusercontent.com/7852916/36447192-d67ff0b4-1640-11e8-99e1-498ef393e2a7.png)

**Comment by amanda-phet** [comment]
I noticed that the Partial Products radio buttons all appear black/gray when disabled, but the "axb" button has color when it is selected. 
![screen shot 2018-02-20 at 1 28 58 pm](https://user-images.githubusercontent.com/7852916/36447524-e76b2e1a-1641-11e8-981b-389d8ac3e7ef.png)
![screen shot 2018-02-20 at 1 29 04 pm](https://user-images.githubusercontent.com/7852916/36447548-eb0fc4ea-1641-11e8-90de-15bdd76dbc09.png)


I think we should do the same thing for the partition radio buttons. It might help distinguish them more, and be consistent with the other buttons.

**Comment by jonathanolson** [comment]
Implemented in the above commit.

**Comment by amanda-phet** [comment]
Looks perfect! Thanks so much.
