### ISSUE TITLE
Make panel and accordion box title larger

### ISSUE THREAD

**Issue by amanda-phet** [phetsims/area-model-common#86]
Across all four sims, can we increase the font size of the titles for the panels and accordion boxes? If the fonts are already the "standard" PhET size, perhaps increase the padding? I noticed that they are very tight in this sim.

For comparison, here are examples from Area Model and Equality Explorer. 
![screen shot 2018-02-16 at 2 14 43 pm](https://user-images.githubusercontent.com/7852916/36329579-b0cf7756-1323-11e8-97d6-3a93dd544c2b.png)
![screen shot 2018-02-16 at 2 14 49 pm](https://user-images.githubusercontent.com/7852916/36329580-b0dfc1ce-1323-11e8-893e-16cb187e2287.png)

Can you let me know if you think increasing the font size is the solution, or increasing the padding inside the accordion box? And if you see consequences of making a change like this.

**Comment by jonathanolson** [comment]
Matched some options with EqEx, can you check how it looks now? (area-model was previously using the defaults, these are technically not default settings now).

**Comment by amanda-phet** [comment]
I like these quite a bit! 

@kathy-phet do you want to take a look and close if these look good to you?

**Comment by kathy-phet** [comment]
Looks good to me.

**Comment by phet-steele** [comment]
@amanda-phet @jonathanolson this has introduced overlap between the calculation box ant the nearby panel in the below scenario:

<img width="1672" alt="screen shot 2018-02-26 at 2 57 43 pm" src="https://user-images.githubusercontent.com/5863899/36697894-8d6699b8-1b05-11e8-9db2-8c8d0691e6dd.png">

**Comment by amanda-phet** [comment]
Yeah, this is not a good situation. We will need to change something about those panels on the right... either remove that padding we added, or make things smaller.

**Comment by kathy-phet** [comment]
I don't think we want reduce the calculation font, so I'm wondering if we can make the padding a bit smaller.

**Comment by amanda-phet** [comment]
One thought is to move the board scene selection combo box to the region that other screens use for similar controls:

(hacked together mockup) 
![screen shot 2018-02-27 at 1 59 37 pm](https://user-images.githubusercontent.com/7852916/36754626-c8ad4e10-1bc6-11e8-889b-7fd8b6fd8b70.png)

**Comment by amanda-phet** [comment]
Also, reducing the font in the calculation panel by 15% effectively solves this problem, but of course the font is slightly smaller. It is still over 13pt though, so it's not a crazy small size. 

![screen shot 2018-02-27 at 2 11 55 pm](https://user-images.githubusercontent.com/7852916/36755070-3b964a7a-1bc8-11e8-836d-94fb45b6ec35.png)

**Comment by amanda-phet** [comment]
@ariel-phet and @kathy-phet thoughts on these options? Any other ideas?

**Comment by ariel-phet** [comment]
@amanda-phet I think reducing the calculation is totally a reasonable solution...however, the spacing between lines in the calculation panel should be increased vertically (the leading as we say).

I think with more space between lines things will still be legible and able to be parsed.

**Comment by kathy-phet** [comment]
If the solution is to decrease the font on the equation, I would only want to do that if necessary... not all the time.

I think it’s important to have it as legible as possible when projected.

My preference is for an alternative solution, but I would be ok with font change if it’s rarely encountered.

K

Sent from my iPhone

On Feb 27, 2018, at 2:49 PM, Ariel Paul <notifications@github.com<mailto:notifications@github.com>> wrote:


@amanda-phet<https://github.com/amanda-phet> I think reducing the calculation is totally a reasonable solution...however, the spacing between lines in the calculation panel should be increased vertically (the leading as we say).

I think with more space between lines things will still be legible and able to be parsed.

**Comment by jonathanolson** [comment]
> If the solution is to decrease the font on the equation, I would only want to do that if necessary... not all the time.

This could be done with a maxWidth (like we use for i18n) where it would only scale down if its size would be too large. The large majority of the time this would not be applied (and it would look the same as before).

**Comment by amanda-phet** [comment]
>This could be done with a maxWidth (like we use for i18n) where it would only scale down if its size would be too large. The large majority of the time this would not be applied (and it would look the same as before). 

I forgot about that possibility. That seems like a great solution, then. Can we make this the cutoff point before resizing? 

<img width="920" alt="screen shot 2018-02-28 at 8 43 34 pm" src="https://user-images.githubusercontent.com/7852916/36826059-266c760a-1cc8-11e8-96a4-ea4dbfc3bef9.png">

**Comment by jonathanolson** [comment]
Implemented. I also added a query parameter ?maximumLayout1 (for now) that fills things out in a way that will trigger the maxWidth.

**Comment by amanda-phet** [comment]
This looks great to me. I hardly notice a change when the font scales and I'm looking for it!

**Comment by amanda-phet** [comment]
I'll make the call that this looks good and doesn't need further tweaking.
