### ISSUE TITLE
Changes to game screens (AMM and AMA) 

### ISSUE THREAD

**Issue by amanda-phet** [phetsims/area-model-common#87]
[note: it seems this issue was never submitted last Wednesday when I originally made it and I am starting over.. so I may realize that I've forgotten something and include follow-up requests in this thread.] 

@kathy-phet and I decided to make some changes to the game screen behavior. This seems more in line with other PhET game behavior, so we should be able to use the vegas game bar component. 

(1) Changes to game bar. This includes using the start over button instead of back, so the level progress is reset when clicking this instead of saving progress. The Level text is bold, and the text is slightly rearranged from how it is right now. The score is displayed as stars (not points). 
![screen shot 2018-02-21 at 11 02 29 am](https://user-images.githubusercontent.com/7852916/36692840-80a3cf5c-1af6-11e8-9c02-cd90623d1f57.png)

(2) Make some changes to the game challenges (not including status bar).
![screen shot 2018-02-21 at 11 14 17 am](https://user-images.githubusercontent.com/7852916/36692996-04d0f00c-1af7-11e8-9c16-26f62ce64537.png)

(2a) The prompt needs to be in the play area, so the model, dimensions, and total area should all be shifted down. The prompt is left-aligned with the Level text, and is large and bold (I can't remember the pt size right now). 
(2b) The total area of model display should be larger, ideally the same as what we see on the generic screen. Right now, the total area (e.g., 1605) is quite small once it is entered. 
(2c) The partial products font also seems smaller here than on the generic screen, so ideally we should increase the font size to match the generic screen.

**Comment by jonathanolson** [comment]
I believe I've handled  (1) and (2a). I adjusted the game button (check/show solution/etc.) and "face" locations to compensate (they went below the bottom with the change in layout).

For (2b) and (2c), it's essentially the same question (as they use the same component internally): Do you only want the value (with NO edit button) to have its size increased, e.g.:
![area-model-game-area-1](https://user-images.githubusercontent.com/480878/37139758-4b5012f2-226c-11e8-8156-a68a04a0a842.PNG)
or do you also want the size of the editable value (presumably before/after entry) to be increased? e.g.:
![area-model-game-area-2](https://user-images.githubusercontent.com/480878/37139786-6bbb5d1c-226c-11e8-97eb-bb89776dc60d.PNG)
and
![area-model-game-area-3](https://user-images.githubusercontent.com/480878/37139789-6f869a88-226c-11e8-880c-fbb3e868b8fc.PNG)

In my opinion, it would be most consistent to have all of these increased, and each "location" of a value could have a different font size. Thus the partial products and total area could be increased.

Thoughts? And how does the current behavior look for everything else?

**Comment by amanda-phet** [comment]
(1) and (2a) are looking great. Thanks!

>In my opinion, it would be most consistent to have all of these increased, and each "location" of a value could have a different font size. Thus the partial products and total area could be increased.

I agree. We should increase the size of both the value AND the editable value. 

And to clarify, here is the discrepancy I'm referring to: in the game, the total area is much smaller than in the generic screen. Also, and it could be my eyes playing tricks, but the partial products seem slightly smaller in the game screen. 
![screen shot 2018-03-13 at 1 46 13 pm](https://user-images.githubusercontent.com/7852916/37366083-0fddefb6-26c5-11e8-98af-b2a15864c9e7.png)

If this pushes the check button down farther, can we move the smiley/frowny face somewhere else? Perhaps to the left of the check button?

**Comment by jonathanolson** [comment]
Implemented, does anything else here need more changes?

The face still fits (it was a slight tweak, so I didn't move it yet), but if you want to move it, would this work?:
![area-model-face-position](https://user-images.githubusercontent.com/480878/37435386-bffdf6be-27a8-11e8-8c7e-57b671b6268a.PNG)

If you want it centered with the check button, we'd need to push the buttons down.

**Comment by amanda-phet** [comment]
I like the location you sketched better than below the button. There is plenty of space and might help it be more visible (especially the score) if someone is using a tablet. Would you mind making the change?

I think the larger text looks great! Thanks.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by jonathanolson** [comment]
Implemented, does that look good?

**Comment by amanda-phet** [comment]
Great. Thanks. Everything was starting to look really low on the screen so I think that helps.

**Comment by pixelzoom** [comment]
Reopening.

I'm having a hard time understanding why the layout here is so entirely different from what was specified in https://github.com/phetsims/vegas/issues/59 for new "standard" game components.  And how this could have happened when @amanda-phet was the designer in both cases. And why @jonathanolson has once again implemented a custom solution (GameStatusBar) instead of using standard vegas components.

**Comment by pixelzoom** [comment]
Reopening.

I'm having a hard time understanding why the layout here is so entirely different from what was specified in https://github.com/phetsims/vegas/issues/59 for new "standard" game components.  How this could have happened when @amanda-phet was the designer in both cases. And why @jonathanolson has once again implemented a custom solution (GameStatusBar) instead of using standard vegas components.  

@ariel-phet I suggest that we have a meeting about this asap.  Further work on vegas is on hold until this is cleared up.

**Comment by pixelzoom** [comment]
@andrea-phet FYI.

**Comment by pixelzoom** [comment]
@amanda-phet I also see that Area Model animates between "settings" and "challenges" in the game.  Why is this the case in Area Model, but not in Equality Explorer?

**Comment by pixelzoom** [comment]
The implementation is also not using level-selection buttons (old or new) from vegas.  Looks like @jonathanolson is creating his own buttons.  I see no good reason for this,  and it's very discouraging.

**Comment by jonathanolson** [comment]
> The implementation is also not using level-selection buttons (old or new) from vegas. Looks like @jonathanolson is creating his own buttons. I see no good reason for this, and it's very discouraging.

Sorry about that. I was used to the last case where make-a-ten couldn't use the common version, and didn't check to see if it would work for area-model. I definitely should have used the common component here.

**Comment by amanda-phet** [comment]
@pixelzoom said 
>I'm having a hard time understanding why the layout here is so entirely different from what was specified in phetsims/vegas#59 for new "standard" game components. 

The layout here is following the standard game components for games with 6 set challenges, based one what I observed in Graphing Lines, Balancing Act, Area Builder, etc. I specifically redesigned it from what Amy H had originally designed to fit that type of game, as opposed to a custom design that didn't match any other PhET games. 

My understanding is the new game components were designed because of the recent games we have designed that have infinite challenges. We made the design flexible enough to account for games that haven't been designed yet, but I didn't think the goal was to make this the new style moving forward for *all* games.

**Comment by pixelzoom** [comment]
@amanda-phet said:
> The layout here is following the standard game components for games with 6 set challenges ...

If that's the case, then why is not using any of the standard vegas components for that type of game? That is, ScoreboardBar, LevelSelectionItemNode, etc.  There's also no reason why it can't use the new score displays, which applicable to both flavors (new and old) of games. 

There are also other differences that don't match older 6-challenge games.  Eg:
https://github.com/phetsims/vegas/issues/64
https://github.com/phetsims/vegas/issues/65

**Comment by pixelzoom** [comment]
Also regarding the score display... 

This is the score display that appears in older 6-challenge games, e.g. RPAL:

![screenshot_554](https://user-images.githubusercontent.com/3046552/38529789-4a0e8578-3c24-11e8-9b24-d56931578c4e.png)

These are the 3 score displays that we agreed on, and implemented, in https://github.com/phetsims/vegas/issues/59#issuecomment-364608714, to be reused throughout old and new-style games:

![screenshot_555](https://user-images.githubusercontent.com/3046552/38529831-873baf70-3c24-11e8-850e-9dc9cba0dc07.png)

And here's what's in Area Model, which doesn't match any of the above:

![screenshot_556](https://user-images.githubusercontent.com/3046552/38529869-b3047eac-3c24-11e8-97ac-173006249212.png)

Why the need for something different?  And if this really needed, why wasn't it added to the design in phetsims/vegas#59?

**Comment by jonathanolson** [comment]
> If that's the case, then why is Area Model not using any of the standard vegas components for that type of game? That is, ScoreboardBar, LevelSelectionItemNode, etc.

RE: LevelSelectionItemNode, that was my mistake.

RE: Others, it was because all of the designs where I have implemented games (make-a-ten, area-model, etc.) deviated significantly in the initial design from existing vegas components. They seemed to be components that could be used in some game sims, but didn't look general enough that they would (without significant effort) work for every game.

It's also why I noted as an explicit entry as part of the code review that we should see what vegas components can NOW be used, given the changes in the sim's design and the changes in vegas components. I definitely don't want to let it slip out the door duplicating common code that would have a higher maintenance cost long-term.

**Comment by pixelzoom** [comment]
Regarding changes to transitions in this sim...  See design consensus in https://github.com/phetsims/vegas/issues/65#issuecomment-380930042

**Comment by pixelzoom** [comment]
@jonathanolson The dissolve transition (for when the "Start Over" button is pressed), should live in twixt.  See https://github.com/phetsims/twixt/issues/6.

**Comment by jonathanolson** [comment]
When I have nothing else to do for this sim (handled pending review items, etc.) I'll do a bit more work on the twixt Animation type (it would be nice to use it to animate the opacity).

**Comment by jonathanolson** [comment]
Main integration work done for vegas. The only thing left is the dissolve.

**Comment by jonathanolson** [comment]
Dissolve implemented. @amanda-phet can you see how it looks?

@samreid can you add TWIXT/Transition and TWIXT/TransitionNode to your review? It would be nice to collaborate on improvements, as it could definitely use some API/deduplication work.

**Comment by jonathanolson** [comment]
Also see TWIXT demo's 4th screen, which shows all of the transitions in action.

**Comment by amanda-phet** [comment]
I really like it! 

@pixelzoom @kathy-phet @ariel-phet you should also review, since this will be the new standard for games with "start over" buttons.

**Comment by ariel-phet** [comment]
Dissolve looks good to me.

**Comment by pixelzoom** [comment]
Dissolve looks good to me too.  Twixt "Transitions" demo page is awesome.

**Comment by samreid** [comment]
> @samreid can you add TWIXT/Transition and TWIXT/TransitionNode to your review? It would be nice to collaborate on improvements, as it could definitely use some API/deduplication work.

I created this issue for review: https://github.com/phetsims/twixt/issues/11

**Comment by amanda-phet** [comment]
Seems this issue can be closed.
