### ISSUE TITLE
Algebra crashes on iPad when all handles move, area model calculation on

### ISSUE THREAD

**Issue by lmulhall-phet** [phetsims/area-model-common#88]
**Test device:**

Dalton

**Operating System:**

iOS 11.2.5

**Browser:**

Safari

**Problem description:**

Algebra will crash if, in the explore screen, both partition line drag handles (red and blue things) and the proportional drag handle (green thing) are moved at the same time while either the line-by-line area model calculation button or the all-lines area model calculation button is selected. (It does not matter which area model calculation button is selected.) The Partial products buttons do not need to be selected to experience crashing. The grid box does not need to be checked. The tile box does not need to be checked. It does not matter if the 20x20 button or the 100x100 button is selected. I think the dimensions dropdown box and the total area of model dropdown box need to be down.

I have only experienced crashing while either the line-by-line area model calculation button or the all-lines area model calculation button is selected. I haven't experienced crashing with the hidden area model calculation button selected. This is for phetsims/QA/issues/99.

**Steps to reproduce:**

1. Go to explore screen.
2. Selected either either the line-by-line area model calculation button or the all-lines area model calculation button.
3. Make sure the dropdown boxes are down.
4. Make sure you drag both partition line drag handles and the proportional drag handle at the same time.
5. Do step 4 until the sim crashes.

**Comment by lmulhall-phet** [comment]
Sorry didn't see phetsims/area-model-common/issues/25 or phetsims/area-model-common/issues/20. Closing.

**Comment by phet-steele** [comment]
This issue is better documented than either of those other issues, so I'm favoring this one. Adding the one comment from @jonathanolson though:

> Creating many Text nodes for RichText seems like an obvious culprit.

**Comment by phet-steele** [comment]
For the sake of memory, AMA loads starting at about 100 MB. After only a few moments following the above steps, AMA grows to use >200 MB.

**Comment by phet-steele** [comment]
@lmulhall-phet this occurs on any screen using a calculation panel, correct?

**Comment by jonathanolson** [comment]
The calculation view is using a not-yet-optimized setup that is leaking a LOT of memory. I'll have that fixed up soon.

**Comment by lmulhall-phet** [comment]
@phet-steele I've only experienced a crash in the explore screen.

**Comment by jonathanolson** [comment]
Partial commit above is a not-yet-complete rewrite of the calculation lines to handle GC and better performance. @phet-steele once it's finished, it would be great to make sure I didn't change any visual behavior.

**Comment by jonathanolson** [comment]
I'll be refining it, but the main commits are pushed to master. It's about a 2k LOC rewrite, so I ran it through snapshot comparison for each sim (500 frame comparisons, where each frame is like 10-20 seconds of normal fuzzing). It isn't showing any visual or behavioral differences, but I'm still not convinced there wasn't a regression.

**Comment by jonathanolson** [comment]
I can't get it to crash with 20min of fuzzing on an iPad2, and memory profiling tools show it isn't leaking. Can you try https://www.colorado.edu/physics/phet/dev/html/area-model-algebra/1.0.0-dev.8/phet/area-model-algebra_en_phet.html to confirm?

It is still QUITE heavy on initial memory, as any "generic" screen ("Generic", "Variables") has 9 copies of the main view (one for each width-x-height combination). This might be slowing performance down also.

@ariel-phet, it would be good to know somewhat soon if the iPad performance/memory is acceptable, or if it would need improvements. Having one view that switches between different models would be the solution (and takes the sim down to a pretty stable 50-60MB of memory), but it would be a day's worth of work. Thoughts?

**Comment by lmulhall-phet** [comment]
@jonathanolson I got it to crash after a few minutes of playing with factors, all-lines, 20x20, and tile checked.

**Comment by lmulhall-phet** [comment]
Should note that I was testing on Tycho, which has different iOS version (9.3.5) and (I would imagine) different Safari version. Would test on Dalton, but it's not in the QA office.

**Comment by jonathanolson** [comment]
Thanks. I'll start looking into the general memory fixes for the sim.

**Comment by jonathanolson** [comment]
Finished the main refactoring and pushed to master (another 2.5k LOC change). This is also a "could break just about everything, and any mistake probably leaks memory" change, so I'll be doing snapshot comparisons and memory profiling to try to catch anything that may have gone wrong.

If there is a memory leak, it's smallish (and ~10min fuzzing still has it under 70MB on Chrome), so I'll be testing iPad crashes.

**Comment by jonathanolson** [comment]
Resolved all regressions, now snapshot comparisons are passing with 500 snapshots / sim.

**Comment by jonathanolson** [comment]
No significant memory leaks either currently, can you test https://www.colorado.edu/physics/phet/dev/olsonjb/area-model/ to see if any crash on the iPad with usage?

**Comment by lmulhall-phet** [comment]
@jonathanolson I spent about 20 minutes trying to get algebra to crash, and I haven't been able to get it to crash! I think it's time to close this issue.
