### ISSUE TITLE
Make partition lines pickable

### ISSUE THREAD

**Issue by phet-steele** [phetsims/area-model-common#89]
I think it would be nice to make the full length of a partition line be pickable. @amanda-phet and @jonathanolson agree.

**Comment by jonathanolson** [comment]
Implemented, can you try it out to see if the areas are sufficient, or should be expanded? It has a slightly expanded "mouse" area so it is possible with the mouse.

**Comment by amanda-phet** [comment]
@phet-steele have you looked at this yet? Can you check on an iPad?

On the computer I think the area is sufficient.

**Comment by phet-steele** [comment]
I did look and totally forgot to say so!
