### ISSUE TITLE
Markdown documentation with images?

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/area-model-common#93]
This sim has a ton of terminology, some of which is difficult to describe. Having something like doc/glossary.md (with checked in images referenced in the .md) that can describe all of the terms used internally would be helpful for documentation (notably for whoever code-reviews or needs to make changes to the sim in the future).

Would that be acceptable, or would there be a better way of accomplishing the documentation with images?

**Comment by jonathanolson** [comment]
https://stackoverflow.com/questions/14494747/add-images-to-readme-md-on-github notes how to include images in the markdown that are checked into the repo.

**Comment by Denz1994** [comment]
Could you make the entry of a term a hyperlink to an image within the .md?  

For example in Unit Rates [implementation notes](https://github.com/phetsims/unit-rates/blob/master/doc/implementation-notes.md) under `Terminology`:

- [scale](https://user-images.githubusercontent.com/13894380/37160276-d7d72d0e-22bd-11e8-9a78-b95b3f08485b.png) - place bags and items here to display their corresponding cost and (for candy) quantity

Alternatively:

- scale - place bags and items here to display their corresponding cost and (for candy) quantity

**Comment by jonathanolson** [comment]
> Could you make the entry of a term a hyperlink to an image within the .md?

I'm totally fine with that if people would prefer it. Might be better if people know many of the terms (so it's easy to scan through).

**Comment by jessegreenberg** [comment]
Could a glossary section fit into doc/implementation-notes.md? I am OK with a long doc/implementation-notes.md.

I think it depends on whether we want a doc/glossary.md in all sims or if it is just for this sim. I would rather not have a special file just for this sim.

**Comment by jonathanolson** [comment]
> Could a glossary section fit into doc/implementation-notes.md? I am OK with a long doc/implementation-notes.md.

Wow, I checked molecule-shapes to see if implementation-notes was in markdown, and it has implementation-notes.txt (so I figured another file would be necessary). I'm totally fine having those in implementation-notes.md, and should I fix up molecule-shapes to have markdown?

**Comment by jessegreenberg** [comment]
I don't know when the decision was made, but I have seen new sims use implementation-notes.md and older sims use implementation-notes.txt. Perhaps the decision was to start using .md but not go back and convert .txt to .md? I would say it is up to you.

**Comment by pixelzoom** [comment]
I generally have a Terminology section in implementation-notes.md.  This has worked out great when interacting with QA.  This also assumes that your design team has clearly defined terminology.  And of course there's "domain terminology" and "implementation terminology".

Examples:
https://github.com/phetsims/function-builder/blob/master/doc/implementation-notes.md
https://github.com/phetsims/unit-rates/blob/master/doc/implementation-notes.md
https://github.com/phetsims/graphing-lines/blob/master/doc/implementation-notes.md

And I generally refer to these Terminology sections in RC issues, e.g.:
https://github.com/phetsims/tasks/issues/638

**Comment by pixelzoom** [comment]
We decided to use .md (implementation-notes.md and model.md) quite awhile ago.

**Comment by jonathanolson** [comment]
Decision was to include images under `doc/images/` and feel free to include in the implementation-notes.md
