### ISSUE TITLE
Decrease range for editable game polynomial coefficients?

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/area-model-common#94]
Currently, the supported range for those coefficients is -99 to 99, but I had a note that these probably wouldn't go outside -81 to 81. I recall we briefly discussed this, but I don't remember the result. Should I change this to -81 to 81?

**Comment by amanda-phet** [comment]
Yes I think we can change the range to [-81,81]. I don't see any reason to go beyond.

**Comment by jonathanolson** [comment]
Implemented.
