### ISSUE TITLE
Does the keypad need expanded touch areas?

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/area-model-common#95]
Currently that isn't supported by the common component, so I haven't done that.

**Comment by amanda-phet** [comment]
I would prefer to make that kind of change to the common component rather than this individual sim. @ariel-phet ?

**Comment by ariel-phet** [comment]
@jonathanolson @amanda-phet - that seems like an important enhancement to the common component, given that we are supporting a wider range of touch devices (with the android app, and things like expanding the iOS app to iphone). 

@jonathanolson please proceed with adding this functionality to the common component if possible

**Comment by jonathanolson** [comment]
Added default touch areas to the Keypad (checked usage in projectile-motion also, looks safe).

Should be done.
