### ISSUE TITLE
Games don't freeze during "Start Over" animation 

### ISSUE THREAD

**Issue by phet-steele** [phetsims/area-model-common#96]
Pressing "Start Over" on a game will start the leftward animation. During this animation, if you keep your eye on the game, you will notice that the challenge has updated. It becomes the first question you would otherwise see when returning to the level.

I don't think this is a big deal, but looks somewhat...ugly...when you notice it.

Seen on macOS 10.13.3 Chrome.

**Comment by jonathanolson** [comment]
Should be fixed with the above commit.

**Comment by phet-steele** [comment]
Fixed for me, thanks.
