### ISSUE TITLE
design screen icons

### ISSUE THREAD

**Issue by amanda-phet** [phetsims/area-model-common#97]

**Comment by amanda-phet** [comment]
@DianaTavares and I have been working on the design of the screen icons. We would appreciate some feedback. We took Amy's ideas and tried to simplify them a bit, but they are still busy icons. However I think they could be fine for the home screen.

**Comment by DianaTavares** [comment]
This are the options for the icons:

![screen shot 2018-03-23 at 11 49 57 am](https://user-images.githubusercontent.com/26031501/37850192-e9a29a9e-2e9f-11e8-91a8-6f1d25ce79b0.png)

![screen shot 2018-03-23 at 11 47 03 am](https://user-images.githubusercontent.com/26031501/37850198-edc13f2c-2e9f-11e8-9a70-569d642c8a8c.png)

![screen shot 2018-03-23 at 1 43 49 pm](https://user-images.githubusercontent.com/26031501/37850308-41b1615c-2ea0-11e8-8f55-4ae09958f03d.png)

what do you think?

**Comment by amanda-phet** [comment]
@ariel-phet and @kathy-phet would love some feedback!

**Comment by amanda-phet** [comment]
We will need a different game icon for the Algebra sim, that shows a problem with variables. But otherwise I think these icons do a good job of illustrating the content of the screens. They are all fairly "busy" but I don't have any great ideas for simplifying further.

**Comment by DianaTavares** [comment]
For the game then I have this option, one like the same but with "x" and other simpler:

![screen shot 2018-03-23 at 3 44 44 pm](https://user-images.githubusercontent.com/26031501/37854590-27a9124e-2eb1-11e8-9c46-0020faeffc44.png)

**Comment by DianaTavares** [comment]
for the  variables view, I think that looks less busy if I change the way of the rectangle (and is more similar to the Partition icon )

![screen shot 2018-03-23 at 3 49 01 pm](https://user-images.githubusercontent.com/26031501/37854739-bc615be4-2eb1-11e8-9949-66bc19a7fd4e.png)

**Comment by ariel-phet** [comment]
@amanda-phet @DianaTavares 

To me all of these have too much detail, and are going to be difficult to see on the nav bar. Please include mockups of the navbar icons at actual size.

A few comments:

1. Why use this "handwriting"/chalkboard style font? It does not appear anywhere in the sim?

2. Those could work for the homescreen, but I think you want to figure out the simplified versions first

3. For instance for the Explore Screen maybe just have the leader lines and the measurement of 10, no 5,5 and 3,7

**Comment by amanda-phet** [comment]
(1) There are a few changes here that do not appear in the sim.. the partition lines are modified to fit larger products inside the model, and the handwriting style font is to spark someone's connection to the models they draw by hand on paper. Another font option I was thinking of was the one we used in Make a Ten, but the one you see here is a simple built-in font in illustrator. 

(2) For the navbar I think we'd simplify these to either just be the problem at the top, or just be the model.

**Comment by DianaTavares** [comment]
This are the new version of the icons: 

**Area Model Introduction**

![screen shot 2018-04-09 at 10 49 07 am](https://user-images.githubusercontent.com/26031501/38510917-aa66d470-3be3-11e8-9479-3d79242e4a86.png)

**Area Model Multiplication**
![screen shot 2018-04-09 at 10 50 57 am](https://user-images.githubusercontent.com/26031501/38510996-e7b0aa90-3be3-11e8-8d62-d0d9cc66b882.png)

**Area Model Algebra**
![screen shot 2018-04-09 at 10 51 59 am](https://user-images.githubusercontent.com/26031501/38511039-0c0daf3c-3be4-11e8-9275-3dc0df412b81.png)

@amanda-phet review them al ready
what do you think @ariel-phet ?

**Comment by amanda-phet** [comment]
This is the "handwriting" font from Make A Ten, by the way. I think it is a nice touch and connects our sim to representations people are already familiar with.

**Comment by DianaTavares** [comment]
sorry, I made a mistake, now this are the new icons for the sim :) 

**Intro**
![screen shot 2018-04-09 at 10 49 07 am](https://user-images.githubusercontent.com/26031501/38511419-61f74182-3be5-11e8-9c66-91db418e8650.png)

**Multiplication     
![screen shot 2018-04-09 at 11 12 07 am](https://user-images.githubusercontent.com/26031501/38511899-e02b2806-3be6-11e8-808b-b1567f6167d9.png)

**Algebra**
![screen shot 2018-04-09 at 11 12 13 am](https://user-images.githubusercontent.com/26031501/38511904-e616a9c0-3be6-11e8-914d-a0537957421e.png)



What do you think @ariel-phet ?

**Comment by kathy-phet** [comment]
I find the mix of the hand numbers and the typed numbers conflicting. I would go all one or the other. The hand ones are fun, I agree. Is there a way to do a hand drawn numbers for the first icon too.

**Comment by ariel-phet** [comment]
These seem to be good in the navbar, clearly different. And the clutter seems nicely reduced.

**Comment by jonathanolson** [comment]
Looks like all home/navbar icons are added now into the sims.
