### ISSUE TITLE
Game level icons

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/area-model-common#98]
Will need numbers 1-6 and variables 1-6.

**Comment by DianaTavares** [comment]
This are the options for AMM (numbers) 
![screen shot 2018-04-13 at 4 16 02 pm](https://user-images.githubusercontent.com/26031501/38760921-155e9dde-3f3c-11e8-88f4-4566a39ce161.png)

Working in AMA

**Comment by jonathanolson** [comment]
These were added into the repo, so I'll work on integration.

**Comment by amanda-phet** [comment]
Commit: https://github.com/phetsims/area-model-common/commit/3e3ee0d3b2abb2da89a3827ad6d2ffc1e5bd6649

**Comment by jonathanolson** [comment]
Added, but it looks like it could use some polishing. The level icons have a lot of unused vertical space in them, which means they get resized down to a slightly smaller size. Additionally, let me know if the height of the overall level buttons should be reduced to better match the size of the icons.

<img width="1122" alt="screen shot 2018-04-19 at 3 56 33 pm" src="https://user-images.githubusercontent.com/480878/39020529-7b2e9fbc-43ea-11e8-9bad-414b4dd8fdbf.png">
<img width="1122" alt="screen shot 2018-04-19 at 3 56 41 pm" src="https://user-images.githubusercontent.com/480878/39020531-7f05b53a-43ea-11e8-853e-ce056ecfdf09.png">

**Comment by jonathanolson** [comment]
Notably there is a lot of empty space on the icons:
<img width="468" alt="screen shot 2018-04-19 at 3 59 31 pm" src="https://user-images.githubusercontent.com/480878/39020582-b184438c-43ea-11e8-87fb-d38572b57d22.png">

I would imagine that maybe we'd have 2-3 pixels of space on each side (vertically and horizontally) for the source images.

If you commit changes to the icons, it will automatically update the layout on the buttons.

**Comment by jonathanolson** [comment]
Additionally, I can manually add padding in code if desired (that's better than padding in the image).

**Comment by amanda-phet** [comment]
I am much happier with the PhET girl icons!
